"""Operator-facing FINAL_PRODUCT_DELTA acceptance for GPU1 preflight.

This is not a proposal-review lane. GPU0/Vulkan remains the reviewer/refiner
surface; this module only prevents preflight transport summaries from being
reported as operator products.
"""

from __future__ import annotations

from typing import Any


TOOL_LOOP_SUMMARY_ERROR = "gpu1_delta_tool_loop_summary_not_operator_product"
PLACEHOLDER_ERROR = "gpu1_delta_placeholder_not_operator_response"

_PLACEHOLDER_PHRASES = (
    "one short paragraph proving",
    "proving you read",
    "confirming that the file has been accessed",
    "this confirms that the file",
    "prodotto operatore richiesto",
    "generato e completato",
    "tutti gli step necessari",
    "generated and completed",
    "all necessary steps",
    "tool execution has been successfully completed",
    "results from the various tools have been processed",
    "review the reports generated by each tool",
    "assistant content is based on the consumed tool results",
    "remain above in this same conversation",
    "are ready for use",
    "il subturn precedente ha provato",
    "scrivi qui il prodotto",
    "<request_id consumed>",
    "questo non",
    "formato se non chiami",
)

_TOOL_LOOP_SUMMARY_PHRASES = (
    "tool loop has reached its soft stop",
    "tool loop has reached its subturn budget",
    "tool execution has reached its subturn budget",
    "following findings have been made",
    "this final product provides a summary of the tool loop execution",
    "summary of the tool loop execution",
    "tool loop execution",
    "tool loop has reached",
    "subturn budget reached",
)

_TOOL_REPORT_SECTION_MARKERS = (
    "toolchain probe",
    "runtime file window",
    "diagnostic tool failures",
    "next steps",
    "tool inventory",
    "agent memory inventory",
    "file references",
    "python syntax check",
    "semantic code chunk",
)


def operator_delta_errors(delta: str, *, response_text: str = "") -> list[str]:
    """Return semantic acceptance errors for an otherwise parsed delta."""
    text = (delta or "").strip().lower()
    full_text = f"{response_text or ''}\n{text}".lower()
    errors: list[str] = []
    if not text:
        return errors
    if any(phrase in text for phrase in _PLACEHOLDER_PHRASES):
        errors.append(PLACEHOLDER_ERROR)
    if _looks_like_tool_loop_summary(text, full_text):
        errors.append(TOOL_LOOP_SUMMARY_ERROR)
    return list(dict.fromkeys(errors))


def operator_delta_report(
    protocol: dict[str, Any],
    *,
    response_text: str = "",
) -> dict[str, Any]:
    """Separate protocol validity from operator-product validity."""
    delta = str(protocol.get("delta") or "")
    errors = operator_delta_errors(delta, response_text=response_text)
    return {
        "passed": bool(protocol.get("passed") is True and not errors),
        "protocol_passed": bool(protocol.get("passed") is True),
        "errors": errors,
        "delta_chars": len(delta),
    }


def invalid_operator_delta_text(
    *,
    delta: str,
    errors: list[str],
    protocol: dict[str, Any],
    provider_report_path: str,
) -> str:
    text = [
        "# GPU1 FINAL_PRODUCT_DELTA",
        "",
        "STATUS: INVALID_OPERATOR_DELTA",
        "",
        "GPU1 produced a valid FINAL_PRODUCT_DELTA protocol, but the delta is not an operator product.",
        f"provider_report: {provider_report_path}",
        "operator_delta_errors:",
        *[f"- {item}" for item in errors],
        "protocol_errors:",
        *[f"- {item}" for item in protocol.get("errors", [])],
        "",
        "## RAW_FINAL_PRODUCT_DELTA",
        "",
        (delta or "").strip(),
    ]
    return "\n".join(text).rstrip() + "\n"


def _looks_like_tool_loop_summary(delta: str, full_text: str) -> bool:
    if any(phrase in delta for phrase in _TOOL_LOOP_SUMMARY_PHRASES):
        return True
    marker_count = sum(1 for marker in _TOOL_REPORT_SECTION_MARKERS if marker in delta)
    meta_terms = (
        "consumed evidence",
        "based on the consumed evidence",
        "findings",
        "tool result",
        "broker request",
        "soft stop",
        "tool loop",
    )
    if marker_count >= 3 and any(term in delta for term in meta_terms):
        return True
    if (
        "close_gpu1_tool_loop_after_soft_stop" in full_text
        and marker_count >= 2
        and any(term in delta for term in ("findings", "next steps", "tool loop"))
    ):
        return True
    return False
