#!/usr/bin/env python3
from __future__ import annotations

from typing import Any


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# OpenVINO GPU.0 observable support workload",
        "",
        f"- Passed: `{report.get('passed')}`",
        f"- Provider execution performed: `{report.get('provider_execution_performed')}`",
        f"- Provider stage: `{report.get('provider_stage')}`",
        f"- Provider work verified: `{report.get('provider_work_verified')}`",
        f"- Provider role counted: `{report.get('provider_role_counted')}`",
        f"- Role rejection reason: `{report.get('role_rejection_reason')}`",
        f"- Provider backend: `{report.get('provider_backend')}`",
        f"- Provider compute device: `{report.get('provider_compute_device')}`",
        f"- Provider device verified: `{report.get('provider_device_verified')}`",
        f"- Device detected: `{report.get('device_detected')}`",
        f"- Model loaded: `{report.get('model_loaded')}`",
        f"- Health check passed: `{report.get('health_check_passed')}`",
        f"- Workload performed: `{report.get('workload_performed')}`",
        f"- Useful output produced: `{report.get('useful_output_produced')}`",
        f"- CPU provider fallback performed: `{report.get('cpu_provider_fallback_performed')}`",
        f"- Device workload execution performed: `{report.get('device_workload_execution_performed')}`",
        f"- Semantic provider required: `{report.get('semantic_provider_required')}`",
        f"- Semantic provider execution performed: `{report.get('semantic_provider_execution_performed')}`",
        f"- Semantic provider model loaded: `{report.get('semantic_provider_model_loaded')}`",
        f"- Semantic provider classification: `{report.get('semantic_provider_classification')}`",
        f"- Production support: `{report.get('production_support')}`",
        f"- Iterations: `{report.get('iterations')}`",
        f"- Minimum seconds: `{report.get('min_seconds')}`",
        f"- Requested role: `{report.get('requested_role')}`",
        f"- Startup manifest: `{report.get('startup_manifest')}`",
        f"- Startup context source: `{report.get('startup_context_source')}`",
        f"- Startup context consumed: `{report.get('startup_context_consumed')}`",
        f"- Leader packet consumed: `{report.get('leader_packet_consumed')}`",
        f"- Leader packet: `{report.get('leader_packet')}`",
        f"- Leader packet heap universe contract: `{report.get('leader_packet_heap_universe_contract')}`",
        f"- Leader packet pointer contract: `{report.get('leader_packet_pointer_contract')}`",
        f"- Leader packet time counter: `{report.get('leader_packet_time_counter_contract')}`",
        f"- Leader packet startup artifacts: `{report.get('leader_packet_startup_artifacts_count')}`",
        f"- Leader packet broker tool evidence: `{report.get('leader_packet_broker_tool_evidence_count')}`",
        f"- GPU.0 visible: `{report.get('openvino_gpu0_visible')}`",
        f"- GPU.0 probe performed: `{report.get('openvino_gpu0_probe_performed')}`",
        f"- GPU.0 workload performed: `{report.get('openvino_gpu0_workload_performed')}`",
        f"- GPU.0 workload passed: `{report.get('openvino_gpu0_workload_passed')}`",
        f"- GPU.0 role: `{report.get('openvino_gpu0_role')}`",
        f"- GPU.0 support lane: `{report.get('openvino_gpu0_support_lane')}`",
        f"- OpenVINO native tool loop requested: `{report.get('native_tool_loop_requested')}`",
        f"- OpenVINO native tool loop supported: `{report.get('native_tool_loop_supported')}`",
        f"- OpenVINO native tool calls: `{report.get('native_tool_call_count')}`",
        f"- GPU.0 observable workload required: `{report.get('openvino_gpu0_observable_workload_required')}`",
        f"- GPU.0 observable workload passed: `{report.get('openvino_gpu0_observable_workload_passed')}`",
        f"- GPU.0 sustained requested: `{report.get('openvino_gpu0_sustained_workload_requested')}`",
        f"- GPU.0 sustained performed: `{report.get('openvino_gpu0_sustained_workload_performed')}`",
        f"- GPU.0 iterations requested: `{report.get('openvino_gpu0_sustained_iterations_requested')}`",
        f"- GPU.0 iterations performed: `{report.get('openvino_gpu0_sustained_iterations_performed')}`",
        f"- GPU.0 min seconds requested: `{report.get('openvino_gpu0_sustained_min_seconds_requested')}`",
        f"- GPU.1 reserved visible: `{report.get('openvino_gpu1_reserved_visible')}`",
        f"- GPU.1 workload performed: `{report.get('openvino_gpu1_workload_performed')}`",
        f"- Selected device: `{report.get('selected_device')}`",
        f"- Available devices: `{report.get('available_devices')}`",
        f"- Elapsed seconds: `{report.get('elapsed_seconds')}`",
        f"- Compile seconds: `{report.get('compile_seconds')}`",
        f"- Inference seconds: `{report.get('inference_seconds')}`",
        "",
        "## Output preview",
        "",
        str(report.get("output_preview") or ""),
        "",
        "## Errors",
    ]
    lines.extend([f"- {item}" for item in report.get("errors") or []] or ["- none"])
    lines.extend(["", "## Warnings"])
    lines.extend([f"- {item}" for item in report.get("warnings") or []] or ["- none"])
    lines.append("")
    return "\n".join(lines)
