"""Allowlisted broker tool registry."""

from __future__ import annotations

from .common import ToolSpec
from .context_builders import (
    build_ai_context_pack_tool,
    build_rag_context_pack_tool,
    build_semantic_evidence_chunk_manifest,
    run_agent_runtime_debug_lab,
    runtime_sqlite_memory,
)
from .inventory_builders import (
    build_agent_agnostic_tool_inventory,
    build_agent_memory_inventory,
    build_agent_transient_request_context,
    build_code_interpreter_report,
    build_python_line_count_csv,
    build_refactor_duplication_audit,
    build_semantic_code_chunk_selection,
    check_python_syntax,
)
from .runtime_builders import (
    analyze_code_product_artifact,
    generic_write,
    run_heap_code_execution_matrix,
    run_heap_virtual_dev_environment,
    runtime_file_refs,
    synthesize_patch_candidates,
)

TOOL_SPECS: dict[str, ToolSpec] = {
    "build_python_line_count_csv": ToolSpec(
        name="build_python_line_count_csv",
        description="Build full Python line-count CSV/JSON/MD evidence.",
        allowed_args=("exclude_dir",),
        builder=build_python_line_count_csv,
    ),
    "build_agent_memory_inventory": ToolSpec(
        name="build_agent_memory_inventory",
        description="Read-only SQLite/JSONL agent memory inventory.",
        allowed_args=("objective", "memory_db"),
        builder=build_agent_memory_inventory,
    ),
    "build_agent_agnostic_tool_inventory": ToolSpec(
        name="build_agent_agnostic_tool_inventory",
        description="Inventory existing reusable IA-Carmine tools and guardrails.",
        allowed_args=("root",),
        builder=build_agent_agnostic_tool_inventory,
    ),
    "build_agent_transient_request_context": ToolSpec(
        name="build_agent_transient_request_context",
        description="Build request-scoped context from memory notes, raw files and reports.",
        allowed_args=(
            "objective",
            "memory_note",
            "raw_file",
            "report_file",
            "max_raw_files",
            "max_chars_per_file",
        ),
        builder=build_agent_transient_request_context,
    ),
    "check_python_syntax": ToolSpec(
        name="check_python_syntax",
        description="Validate Python syntax across repository.",
        allowed_args=(),
        builder=check_python_syntax,
    ),
    "build_code_interpreter_report": ToolSpec(
        name="build_code_interpreter_report",
        description="Build static code-interpreter style report over selected roots.",
        allowed_args=("input",),
        builder=build_code_interpreter_report,
    ),
    "refactor_duplication_audit": ToolSpec(
        name="refactor_duplication_audit",
        description="Build a report-only duplicated-helper/refactor audit over selected code roots and existing evidence reports.",
        allowed_args=(
            "root",
            "report",
            "input_audit_report",
            "line_count_report",
            "code_interpreter_report",
            "python_syntax_report",
            "bundle_smoke_report",
            "memory_routing_report",
        ),
        builder=build_refactor_duplication_audit,
    ),
    "select_semantic_code_chunks": ToolSpec(
        name="select_semantic_code_chunks",
        description="Select bounded semantic code chunks for provider context from current source or an explicit chunk index.",
        allowed_args=(
            "query",
            "chunks",
            "output",
            "markdown_output",
            "max_chunks",
            "max_total_chars",
            "max_excerpt_chars",
            "path_boost",
            "no_code",
        ),
        builder=build_semantic_code_chunk_selection,
    ),
    "ai_context_pack": ToolSpec(
        name="ai_context_pack",
        description="Build a bounded final AI context pack from stable project profiles.",
        allowed_args=(
            "profile",
            "basename",
            "output_dir",
            "evidence_dir",
            "evidence_basename",
            "max_total_chars",
            "max_file_chars",
            "no_evidence",
        ),
        builder=build_ai_context_pack_tool,
    ),
    "semantic_evidence_chunks": ToolSpec(
        name="semantic_evidence_chunks",
        description="Build linked semantic evidence chunks with previous/next context and deterministic summaries.",
        allowed_args=(
            "basename",
            "source",
            "output_dir",
            "chunk_output_dir",
            "chunk_max_chars",
            "chunk_overlap_lines",
            "zip_output",
        ),
        builder=build_semantic_evidence_chunk_manifest,
    ),
    "rag_context_pack": ToolSpec(
        name="rag_context_pack",
        description="Build a heap-consumable internal RAG context pack from SQLite/FTS5/vector retrieval.",
        allowed_args=(
            "query",
            "task_file",
            "db",
            "top_k",
            "char_budget",
            "embedding_endpoint",
            "embedding_model",
            "skip_query_embedding",
            "allow_missing_query_embedding",
            "allow_empty_results",
        ),
        builder=build_rag_context_pack_tool,
    ),
    "agent_runtime_debug_lab": ToolSpec(
        name="agent_runtime_debug_lab",
        description="Run the controlled report-only Python debug lab with an in-memory or allowlisted request.",
        allowed_args=(
            "request_file",
            "request_json",
            "output",
            "markdown_output",
            "timeout_seconds",
            "tail_chars",
        ),
        builder=run_agent_runtime_debug_lab,
    ),
    "runtime_sqlite_memory": ToolSpec(
        name="runtime_sqlite_memory",
        description="Use protected persistent SQLite read-only or operational scratch SQLite memory under output/**.",
        allowed_args=(
            "action",
            "scope",
            "database",
            "persistent_database",
            "summary",
            "content",
            "role",
            "tag",
            "query",
            "limit",
            "confirm",
            "allow_persistent_write",
        ),
        builder=runtime_sqlite_memory,
    ),
    "run_heap_code_execution_matrix": ToolSpec(
        name="run_heap_code_execution_matrix",
        description="Generate and execute a guarded compile/test/diff matrix for concrete heap code proposals.",
        allowed_args=(
            "target_file",
            "validation_script",
            "validation_arg",
            "timeout_seconds",
            "tail_chars",
            "max_diff_chars",
            "operator_request",
            "operator_request_file",
            "evidence_report",
            "synthesize_patch_candidates",
            "force_patch_candidate_synthesis",
            "max_patch_candidates",
            "no_execute",
        ),
        builder=run_heap_code_execution_matrix,
    ),
    "synthesize_patch_candidates": ToolSpec(
        name="synthesize_patch_candidates",
        description="Create artifact-owned validated patch candidates from verified local source targets.",
        allowed_args=(
            "target_file",
            "operator_request",
            "operator_request_file",
            "evidence_report",
            "matrix_report",
            "max_candidates",
            "timeout_seconds",
        ),
        builder=synthesize_patch_candidates,
    ),
    "generic_write": ToolSpec(
        name="generic_write",
        description="Write report-only refined request/action-plan evidence for the next GPU1 turn when code is not yet safely producible.",
        allowed_args=(
            "request_file",
            "operator_request",
            "provider_report",
            "proposal_text",
            "capture_mode",
            "evidence_report",
            "source_lane",
            "source_revision",
            "gpu1_followup_required",
            "peer_followup_required",
            "provider_role",
            "reason",
        ),
        builder=generic_write,
    ),
    "run_heap_virtual_dev_environment": ToolSpec(
        name="run_heap_virtual_dev_environment",
        description="Probe target scripts in a controlled virtual development environment with AST, import, help, compile and product-check evidence.",
        allowed_args=(
            "target_file",
            "validation_script",
            "timeout_seconds",
            "tail_chars",
            "dynamic_import",
            "help_probe",
        ),
        builder=run_heap_virtual_dev_environment,
    ),
    "runtime_file_refs": ToolSpec(
        name="runtime_file_refs",
        description="Resolve provider/operator file refs into local patchable targets, validation refs and rejected artifact refs.",
        allowed_args=(
            "text",
            "text_file",
            "target_file",
            "validation_script",
            "provenance",
            "strict_patchable_targets",
        ),
        builder=runtime_file_refs,
    ),
    "analyze_code_product_artifact": ToolSpec(
        name="analyze_code_product_artifact",
        description="Analyze CODE_PRODUCT_FULL_PATCH artifacts and optionally apply only safe forward-applicable sections.",
        allowed_args=("code_product", "require_all_integrated", "apply_safe", "confirm"),
        builder=analyze_code_product_artifact,
    ),
}
