"""Reusable ready metric fixture for terminal invariant smokes."""

from __future__ import annotations

from typing import Any


def ready_metrics() -> dict[str, Any]:
    return {
        "heap_read_count": 1,
        "heap_write_count": 1,
        "tool_request_count": 1,
        "tool_execution_count": 1,
        "decision_count": 1,
        "candidate_operation_count": 1,
        "product_status": "ready",
        "budget_exhausted": False,
        "provider_lane_count": 3,
        "provider_launch_started": True,
        "pre_provider_phase": False,
        "provider_start_missing_requirements": [],
        "provider_start_unattempted_requirement": "",
        "provider_textual_tool_call_count": 0,
        "provider_native_tool_loop_requested_count": 3,
        "provider_native_tool_loop_supported_count": 3,
        "provider_native_tool_missing_lanes": [],
        "missing_provider_lanes": [],
        "provider_native_tool_unavailable_required_lanes": [],
        "provider_native_tool_missing_required_lanes": [],
        "provider_semantic_missing_required_lanes": [],
        "provider_raw_response_text_chars": len("GPU1 response with source-backed product evidence."),
        "proposal_iteration_artifacts": ["output/validation/proposal_iteration_000.json"],
        "gpu1_closure_decision_packet_valid": True,
        "latest_gpu1_decision": "finalize_product",
        "latest_gpu1_block_id": "smoke:proposal:000",
        "latest_gpu1_revision": "0",
        "latest_gpu1_refine_continuity": {"required": False, "passed": True, "errors": []},
        "latest_proposal_quality_passed": True,
        "latest_proposal_exit_decision": "PATCHABLE_TARGET",
        "gpu0_secondary_schema_valid": True,
        "latest_gpu0_review_decision": "congruent",
        "latest_gpu0_model_decision": "congruent",
        "latest_gpu0_effective_decision": "congruent",
        "latest_gpu0_checked_current_packet": True,
        "latest_gpu0_packet_stale_after_gpu1_packet_rewrite": False,
        "latest_gpu1_block_requires_gpu0_review": True,
        "latest_gpu1_block_reviewed_by_gpu0": True,
        "gpu0_review_invalid_requires_gpu1_retry": False,
        "latest_gpu0_role_decision": "agree_close",
        "latest_gpu0_veto_reasons": [],
        "latest_gpu0_incongruence_reasons": [],
        "latest_gpu0_free_text_used_as_product": False,
        "latest_gpu0_free_text_used_as_decision": False,
        "latest_gpu0_missing_delta_sections": [],
        "latest_final_product_kind": "text_and_code",
        "latest_final_product_action": "append",
        "latest_final_product_delta_valid": True,
        "latest_final_product_pointer_protocol_operational": True,
        "latest_final_product_protocol_errors": [],
        "latest_final_product_requires_file_read": True,
        "latest_final_product_file_read_verified": True,
        "latest_final_product_file_read_refs": ["output/validation/runtime_file_window.json"],
        "latest_final_product_file_read_errors": [],
        "latest_final_product_file_read_tool_api_ready": True,
        "latest_final_product_file_read_tool_api_errors": [],
        "latest_final_product_file_read_result_count": 1,
        "latest_final_product_consumed_file_read_result_count": 1,
        "latest_final_product_diff_present": True,
        "npu_micro_activity_ok": True,
        "generic_write_followup_pending_count": 0,
        "gpu0_peer_followup_pending_count": 0,
        "npu_peer_followup_pending_count": 0,
        "generic_write_capture_failed_count": 0,
        "generic_write_document_product": {"eligible": False},
        "generic_write_refined_product": {"eligible": False},
        "context_hierarchy_valid": True,
        "gpu1_replight_valid": True,
        "gpu1_primary_workload_valid": True,
        "gpu1_primary_evidence_valid": True,
        "gpu1_primary_evidence_source": "native_tool_result",
        "leader_source": "native_tool_result",
        "gpu1_native_tool_call_count": 1,
        "gpu1_boot_leader_ready": True,
        "sidecars_start_policy": "after_gpu1_residency_handshake",
        "parallel_provider_overlap_seconds": 3.5,
        "gpu1_primary_workload_chars": 1200,
        "gpu1_primary_workload_tokens": 128,
        "gpu1_leader_valid": True,
        "gpu1_one_turn_runtime_gate_present": True,
        "gpu1_one_turn_runtime_gate_path": "output/validation/gpu1_one_turn_runtime_gate.json",
        "gpu1_one_turn_runtime_gate_passed": True,
        "gpu1_one_turn_native_tool_call_count": 1,
        "gpu1_one_turn_broker_request_count": 1,
        "gpu1_one_turn_broker_result_count": 1,
        "gpu1_one_turn_broker_result_passed_count": 1,
        "gpu1_one_turn_role_tool_reinjected": True,
        "gpu1_one_turn_tool_result_consumed": True,
        "gpu1_one_turn_final_product_protocol_valid": True,
        "gpu1_one_turn_operator_delta_valid": True,
        "gpu1_one_turn_final_product_delta_valid": True,
        "gpu1_one_turn_blocker": "",
        "gpu1_one_turn_errors": [],
        "gpu1_consumed_gpu0_peer": True,
        "gpu1_consumed_npu_peer": True,
        "context_artifact_refs": ["output/validation/context.json"],
        "response_text_complete": True,
        "quality_output_passed": True,
        "virtual_dev_environment_required": True,
        "virtual_dev_environment_passed": True,
        "code_execution_matrix_required": True,
        "code_execution_matrix_passed": True,
        "patch_candidate_synthesis_required": True,
        "matrix_verified_target_count": 1,
        "concrete_code_proposal_count": 1,
        "runtime_debug_lab_required": True,
        "runtime_debug_lab_passed": True,
    }
