import json
import math
import os
from pathlib import Path

# ============================================================
# PROJECT PATHS
# ============================================================
ROOT = Path(os.environ.get("BAP_ROOT", Path.home() / "blender")).expanduser().resolve()
PROJECT_DIR = (
    Path(os.environ.get("BAP_PROJECT_DIR", ROOT / "blender-audio-project")).expanduser().resolve()
)
OUTPUT_DIR = Path(os.environ.get("BAP_OUTPUT_DIR", PROJECT_DIR / "output")).expanduser().resolve()
ASSETS_DIR = Path(os.environ.get("BAP_ASSETS_DIR", ROOT / "assets")).expanduser().resolve()
AUDIO_DIR = Path(os.environ.get("BAP_AUDIO_DIR", ROOT / "audio")).expanduser().resolve()
RENDERS_DIR = Path(os.environ.get("BAP_RENDERS_DIR", ROOT / "renders")).expanduser().resolve()
SCRIPTING_DIR = PROJECT_DIR / "Scripting" / "v61b"

ANALYSIS_JSON_PATH = OUTPUT_DIR / "Feel The Light-Luca Vera_Master_analysis.json"
AUDIO_PATH = AUDIO_DIR / "Feel The Light-Luca Vera_Master.wav"
OUTPUT_MP4 = RENDERS_DIR / "spaziotempo_asset_visual_v61b.mp4"
OUTPUT_IMAGE_SEQUENCE_DIR = RENDERS_DIR / "spaziotempo_asset_visual_v61b_frames"
OUTPUT_IMAGE_SEQUENCE_PREFIX = "spaziotempo_v61b_"

WORKFLOW_SESSION_PATH = OUTPUT_DIR / "spaziotempo_workflow_session.json"
WORKFLOW_SESSION_ACTIVE = False
WORKFLOW_SESSION_ARTIFACTS = {}

if WORKFLOW_SESSION_PATH.exists():
    try:
        _workflow_session = json.loads(WORKFLOW_SESSION_PATH.read_text(encoding="utf-8"))
        if _workflow_session.get("use_session_track") and isinstance(
            _workflow_session.get("artifacts"), dict
        ):
            WORKFLOW_SESSION_ACTIVE = True
            WORKFLOW_SESSION_ARTIFACTS = _workflow_session["artifacts"]
            ANALYSIS_JSON_PATH = Path(
                WORKFLOW_SESSION_ARTIFACTS.get("analysis_json", ANALYSIS_JSON_PATH)
            )
            AUDIO_PATH = Path(WORKFLOW_SESSION_ARTIFACTS.get("audio_path", AUDIO_PATH))
            OUTPUT_MP4 = Path(WORKFLOW_SESSION_ARTIFACTS.get("render_mp4", OUTPUT_MP4))
            OUTPUT_IMAGE_SEQUENCE_DIR = Path(
                WORKFLOW_SESSION_ARTIFACTS.get("render_frames_dir", OUTPUT_IMAGE_SEQUENCE_DIR)
            )
            OUTPUT_IMAGE_SEQUENCE_PREFIX = str(
                WORKFLOW_SESSION_ARTIFACTS.get("render_frame_prefix", OUTPUT_IMAGE_SEQUENCE_PREFIX)
            )
    except Exception:
        WORKFLOW_SESSION_ACTIVE = False
# ============================================================
# MASTER SWITCHES
# ============================================================
FINAL_FOR_YOUTUBE = False
YOUTUBE_FINAL_RESOLUTION = "1440P"  # 1080P, 1440P, 4K

CLEAR_SCENE = True
CLEAR_SEQUENCER = True
FPS_OVERRIDE = None
RENDER_OUTPUT_MODE = "IMAGE_SEQUENCE"  # IMAGE_SEQUENCE or MP4

YOUTUBE_FINAL_RESOLUTION = str(YOUTUBE_FINAL_RESOLUTION).upper()
if FINAL_FOR_YOUTUBE and YOUTUBE_FINAL_RESOLUTION == "4K":
    RENDER_RESOLUTION_X = 3840
    RENDER_RESOLUTION_Y = 2160
elif FINAL_FOR_YOUTUBE and YOUTUBE_FINAL_RESOLUTION == "1080P":
    RENDER_RESOLUTION_X = 1920
    RENDER_RESOLUTION_Y = 1080
elif FINAL_FOR_YOUTUBE:
    RENDER_RESOLUTION_X = 2560
    RENDER_RESOLUTION_Y = 1440
else:
    RENDER_RESOLUTION_X = 1920
    RENDER_RESOLUTION_Y = 1080

USE_4K = RENDER_RESOLUTION_X >= 3840
RENDER_PERCENT = 100 if FINAL_FOR_YOUTUBE else 75
USE_MOTION_BLUR = True if FINAL_FOR_YOUTUBE else False

EEVEE_TAA_RENDER_SAMPLES = 64 if FINAL_FOR_YOUTUBE else 40
VOLUMETRIC_SAMPLES = 24 if FINAL_FOR_YOUTUBE else 12
VOLUMETRIC_TILE_SIZE = "8"

USE_COMPOSITING = True
COMPOSITOR_GLARE_THRESHOLD_MIN = 1.05
COMPOSITOR_GLARE_THRESHOLD_MAX = 1.62 if FINAL_FOR_YOUTUBE else 1.48
COMPOSITOR_GLARE_MIX = -0.78
COMPOSITOR_GLARE_SIZE = 6
COMPOSITOR_LENS_DISTORT_MIN = 0.000
COMPOSITOR_LENS_DISTORT_MAX = 0.010 if FINAL_FOR_YOUTUBE else 0.006
COMPOSITOR_LENS_DISPERSION_MIN = 0.000
COMPOSITOR_LENS_DISPERSION_MAX = 0.012 if FINAL_FOR_YOUTUBE else 0.007

# ============================================================
# OUTPUT
# ============================================================
VIDEO_BITRATE = 40000 if USE_4K else (24000 if FINAL_FOR_YOUTUBE else 12000)
VIDEO_MAXRATE = 45000 if USE_4K else (30000 if FINAL_FOR_YOUTUBE else 16000)
VIDEO_MINRATE = 0
VIDEO_BUFFERSIZE = 1792
AUDIO_BITRATE = 320
IMAGE_SEQUENCE_FORMAT = "PNG"
IMAGE_SEQUENCE_COLOR_DEPTH = "16"
IMAGE_SEQUENCE_COMPRESSION = 15
ENCODE_SEQUENCE_AUTO_RENDER = False
ENCODE_SEQUENCE_SYNC_AUDIO_TO_FRAME_NUMBER = True
ENCODE_SEQUENCE_AUDIO_ZERO_FRAME = 1
ENCODE_SEQUENCE_SKIP_PLACEHOLDERS = True
ENCODE_SEQUENCE_SWITCH_TO_SEQUENCER = True
ENCODE_USE_EXTERNAL_FFMPEG = True
FFMPEG_EXE_PATH = ""
FFMPEG_OUTPUT_SUFFIX = "_ffmpeg"
FFMPEG_OUTPUT_MP4 = OUTPUT_MP4.with_name(
    f"{OUTPUT_MP4.stem}{FFMPEG_OUTPUT_SUFFIX}{OUTPUT_MP4.suffix}"
)
FFMPEG_LAUNCH_VISIBLE_SHELL = False
FFMPEG_PROFILE = (
    "GPU_AV1_YOUTUBE_SAFE"  # GPU_AV1_YOUTUBE_SAFE, X264_HIGH_QUALITY, CPU_SVTAV1_YOUTUBE
)
FFMPEG_GPU_INDEX = 0
FFMPEG_NVENC_PRESET = "p7"
FFMPEG_NVENC_TUNE = "hq"
FFMPEG_NVENC_CQ = 18
FFMPEG_CRF = 16 if FINAL_FOR_YOUTUBE else 17
FFMPEG_PRESET = "slow"
FFMPEG_TUNE = "film"
FFMPEG_SVTAV1_PRESET = 4
FFMPEG_SVTAV1_CRF = 18 if FINAL_FOR_YOUTUBE else 24
FFMPEG_THREADS = 12
FFMPEG_VIDEO_FILTER = "eq=brightness=0.018:contrast=1.015:saturation=1.04,format=yuv420p"
FFMPEG_AUDIO_BITRATE = "384k"
FFMPEG_AUDIO_SAMPLE_RATE = 48000
# ============================================================
# HERO ASSET
# ============================================================
PRIMARY_ASSET_DIR = ASSETS_DIR / "ball" / "source"
SUPPORTED_ASSET_EXTENSIONS = [".fbx", ".glb", ".gltf", ".obj", ".blend"]
PRIMARY_KEEP_INTERNAL_ANIMATION = False
# ============================================================
# SECONDARY ASSET
# ============================================================
USE_SECONDARY_ASSET = False
SECONDARY_ASSET_DIR = ASSETS_DIR / "ball" / "source"

SECONDARY_TARGET_SIZE = 1.00 if FINAL_FOR_YOUTUBE else 0.90
SECONDARY_BASE_Z = 0.55

SECONDARY_BASE_OFFSET_X = 2.35
SECONDARY_BASE_OFFSET_Y = -0.75
SECONDARY_BASE_OFFSET_Z = 0.00

SECONDARY_SCALE_MIN = 0.88
SECONDARY_SCALE_MAX = 1.18
SECONDARY_BOUNCE_Z = 0.22

SECONDARY_DRIFT_X = 0.36
SECONDARY_DRIFT_Y = 0.24

SECONDARY_ROT_Z = math.radians(14.0)
SECONDARY_ROT_X = math.radians(6.0)


# ============================================================
# VIEW / BLOOM / WORLD
# ============================================================
VIEW_EXPOSURE = -0.07
VIEW_GAMMA = 1.0

USE_BLOOM = True
BLOOM_THRESHOLD = 1.20
BLOOM_INTENSITY = 0.02 if FINAL_FOR_YOUTUBE else 0.018

WORLD_STRENGTH = 0.085 if FINAL_FOR_YOUTUBE else 0.075
WORLD_CAMERA_STRENGTH = 0.58 if FINAL_FOR_YOUTUBE else 0.52
WORLD_LIGHT_COLOR = (0.012, 0.052, 0.058, 1.0)
WORLD_CAMERA_COLOR = (0.045, 0.170, 0.185, 1.0)

USE_HDRI_WORLD = False
HDRI_PATH = ASSETS_DIR / "hdri" / "EveningSkyHDRI037A_4K" / "EveningSkyHDRI037A_4K_HDR.exr"
HDRI_STRENGTH = 0.08 if FINAL_FOR_YOUTUBE else 0.12
HDRI_ROT_Z = math.radians(110.0)

# ============================================================
# SCENE SCALE / COMPOSITION
# ============================================================
FLOOR_SIZE = 44.0
FLOOR_RENDER_VISIBLE = False
FLOOR_VIEWPORT_VISIBLE = True

USE_SOFT_BACKDROP = True
BACKDROP_SIZE = 92.0
BACKDROP_LOCATION = (0.0, 12.0, 5.2)
BACKDROP_ROT_X = math.radians(90.0)
BACKDROP_EMISSION_MIN = 0.145
BACKDROP_EMISSION_MAX = 0.245 if FINAL_FOR_YOUTUBE else 0.205
BACKDROP_BREATHE_SCALE = 0.002

USE_INVISIBLE_COLLISION_PLANE = True
INVISIBLE_COLLISION_PLANE_SIZE = 40.0
INVISIBLE_COLLISION_PLANE_Z = -0.018

PRIMARY_TARGET_SIZE = 2.35
PRIMARY_BASE_Z = 0.72

AURA_RADIUS = 1.62
USE_HERO_AURA_MESH = False
AURA_EMIT_MIN = 0.10 if FINAL_FOR_YOUTUBE else 0.08
AURA_DEFORM_KEYFRAME_STEP = 2
AURA_DEFORM_SUBDIV_VIEW = 1
AURA_DEFORM_SUBDIV_RENDER = 2 if FINAL_FOR_YOUTUBE else 1
AURA_DEFORM_FIELD_RADIUS = 0.72
AURA_DEFORM_DISPLACE_MIN = 0.000
AURA_DEFORM_DISPLACE_MAX = 0.155 if FINAL_FOR_YOUTUBE else 0.110
AURA_DEFORM_DETAIL_MAX = 0.060 if FINAL_FOR_YOUTUBE else 0.042
AURA_DEFORM_WAVE_HEIGHT_MAX = 0.180 if FINAL_FOR_YOUTUBE else 0.125
AURA_DEFORM_FIELD_STRENGTH_MAX = 0.42 if FINAL_FOR_YOUTUBE else 0.30
AURA_DEFORM_FIELD_DRIFT = 0.34
AURA_DEFORM_FIELD_SCALE = 0.22

RING_EMIT_MIN = 0.06 if FINAL_FOR_YOUTUBE else 0.05
RIBBON_EMIT_MIN = 0.08 if FINAL_FOR_YOUTUBE else 0.06
CREATE_VARIANTS = False
VARIANT_COUNT = 4 if FINAL_FOR_YOUTUBE else 2
VARIANT_RING_RADIUS = 3.40
VARIANT_SCALE_MIN = 0.20
VARIANT_SCALE_MAX = 0.34

ENERGY_RING_COUNT = 0
RIBBON_COUNT = 0

USE_MIST_PARTICLES = True
MIST_PARTICLE_COUNT = 18 if FINAL_FOR_YOUTUBE else 12
MIST_SCALE_MIN = 0.75
MIST_SCALE_MAX = 1.35

USE_PHYSICS_ACCENTS = True
PHYSICS_ACCENT_COUNT = 18 if FINAL_FOR_YOUTUBE else 12
PHYSICS_ORBIT_RADIUS_MIN = 1.65
PHYSICS_ORBIT_RADIUS_MAX = 3.85
PHYSICS_ATOM_ORBIT_SPEED_MIN = 0.0048
PHYSICS_ATOM_ORBIT_SPEED_MAX = 0.0125
PHYSICS_ATOM_ORBIT_AUDIO_SPEED = 0.010
PHYSICS_ATOM_ORBIT_RADIUS_PULSE = 0.105
PHYSICS_ATOM_ORBIT_HEIGHT_SWAY = 0.36
PHYSICS_ATOM_MICRO_WOBBLE = 0.075
TETHER_SPRING_STIFFNESS = 8.5
TETHER_SPRING_DAMPING = 0.85

USE_RHYTHM_PARTICLE_PHYSICS = False
RHYTHM_PARTICLE_COUNT = 1100 if FINAL_FOR_YOUTUBE else 620
RHYTHM_DUST_PARTICLE_COUNT = 680 if FINAL_FOR_YOUTUBE else 340
RHYTHM_STREAK_PARTICLE_COUNT = 420 if FINAL_FOR_YOUTUBE else 220
RHYTHM_PARTICLE_LIFETIME = 88
RHYTHM_DUST_LIFETIME = 150
RHYTHM_PARTICLE_EMITTER_RADIUS = 1.42
RHYTHM_PARTICLE_EMITTER_Z = PRIMARY_BASE_Z + 0.86
RHYTHM_PARTICLE_SOURCE_RADIUS = 0.085
RHYTHM_PARTICLE_SIZE_MIN = 0.42
RHYTHM_PARTICLE_SIZE_MAX = 1.08
RHYTHM_PARTICLE_NORMAL_MIN = 0.18
RHYTHM_PARTICLE_NORMAL_MAX = 2.45
RHYTHM_PARTICLE_TANGENT_MIN = 0.10
RHYTHM_PARTICLE_TANGENT_MAX = 1.38
RHYTHM_PARTICLE_BROWNIAN_MIN = 0.18
RHYTHM_PARTICLE_BROWNIAN_MAX = 1.55
RHYTHM_PARTICLE_EMIT_MIN = 0.20
RHYTHM_PARTICLE_EMIT_MAX = 2.30
RHYTHM_PARTICLE_KEYFRAME_STEP = 2

USE_ALBUM_LETTER_PARTICLES = False
ALBUM_PARTICLE_TEXT = "FEEL THE LIGHT"
PARTICLE_SOURCE_LOCATION = (42.0, 42.0, -12.0)
ALBUM_LETTER_PARTICLE_COUNT = 560 if FINAL_FOR_YOUTUBE else 300
ALBUM_LETTER_PARTICLE_LIFETIME = 112
ALBUM_LETTER_SOURCE_SIZE = 0.62
ALBUM_LETTER_EXTRUDE = 0.055
ALBUM_LETTER_EMISSION_STRENGTH = 1.25
ALBUM_LETTER_PARTICLE_SIZE_MIN = 0.52
ALBUM_LETTER_PARTICLE_SIZE_MAX = 1.38
ALBUM_LETTER_ROOT_SCALE_MIN = 0.85
ALBUM_LETTER_ROOT_SCALE_MAX = 1.42

ATMOSPHERE_CUBE_SIZE = 18.0

# ============================================================
# ATMOSPHERE / FOG
# ============================================================
FOG_VOLUME_ENABLED = False
FOG_VOLUME_VIEWPORT_VISIBLE = False
FOG_FILAMENTS_ENABLED = True
FOG_FILAMENT_COUNT = 26 if FINAL_FOR_YOUTUBE else 22
FOG_FILAMENT_KEYFRAME_STEP = 2
FOG_FILAMENT_ALPHA_MIN = 0.160
FOG_FILAMENT_ALPHA_MAX = 0.460 if FINAL_FOR_YOUTUBE else 0.380
FOG_FILAMENT_EMISSION_MIN = 0.055
FOG_FILAMENT_EMISSION_MAX = 0.220 if FINAL_FOR_YOUTUBE else 0.170
FOG_FILAMENT_WIDTH_MIN = 5.8
FOG_FILAMENT_WIDTH_MAX = 13.5
FOG_FILAMENT_HEIGHT_MIN = 0.85
FOG_FILAMENT_HEIGHT_MAX = 2.40
FOG_FILAMENT_DEPTH_MIN = 4.4
FOG_FILAMENT_DEPTH_MAX = 10.8
FOG_FILAMENT_Z_MIN = 1.55
FOG_FILAMENT_Z_MAX = 7.2
FOG_FILAMENT_WIND_DRIFT = 0.58
FOG_FILAMENT_COMPACT_SCALE = 0.32
FOG_FILAMENT_NOISE_SCALE_MIN = 3.8
FOG_FILAMENT_NOISE_SCALE_MAX = 8.5
FOG_FILAMENT_WAVE_SCALE_MIN = 1.2
FOG_FILAMENT_WAVE_SCALE_MAX = 4.8

FOG_DENSITY_MIN = 0.016
FOG_DENSITY_MAX = 0.060 if FINAL_FOR_YOUTUBE else 0.045

FOG_EMISSION_MIN = 0.001
FOG_EMISSION_MAX = 0.009 if FINAL_FOR_YOUTUBE else 0.006

FOG_NOISE_SCALE_MIN = 0.52
FOG_NOISE_SCALE_MAX = 2.70
FOG_RAMP_LOW_BASE = 0.28
FOG_RAMP_HIGH_BASE = 0.54
FOG_CLUMP_SCALE_MIN = 0.34
FOG_CLUMP_SCALE_MAX = 1.35
FOG_CLUMP_RAMP_LOW_BASE = 0.36
FOG_CLUMP_RAMP_HIGH_BASE = 0.58
FOG_CLUMP_WEIGHT_MIN = 0.72
FOG_CLUMP_WEIGHT_MAX = 1.35
FOG_COMPACT_XY = 0.32
FOG_EXPAND_Z = 0.24
FOG_CONTROLLER_DRIFT = 0.42
FOG_WAVE_SCALE_MIN = 0.85
FOG_WAVE_SCALE_MAX = 3.20
FOG_WAVE_DISTORTION_MIN = 5.0
FOG_WAVE_DISTORTION_MAX = 16.0
FOG_WAVE_WEIGHT_MIN = 0.18
FOG_WAVE_WEIGHT_MAX = 0.58
FOG_WIND_SHEAR_X = 0.34
FOG_WIND_SHEAR_Y = 0.24

FOG_DRIFT_SPEED_X = 0.0050
FOG_DRIFT_SPEED_Y = 0.0038
FOG_DRIFT_SPEED_Z = 0.0021

# ============================================================
# HERO AUDIO REACTION
# ============================================================
HERO_SCALE_MIN = 0.88
HERO_SCALE_MAX = 1.40
HERO_BOUNCE_Z = 0.52
HERO_ROT_Z = math.radians(16.0)
HERO_ROT_X = math.radians(8.5)
HERO_ROT_Y = math.radians(6.0)
HERO_DRIFT_X = 0.40
HERO_DRIFT_Y = 0.28
HERO_ORBIT_X = 0.16
HERO_ORBIT_Y = 0.12
HERO_BEAT_TWIST_Z = math.radians(7.5)
HERO_ONSET_SHAKE = math.radians(3.2)

USE_HERO_MESH_DEFORM = True
HERO_DEFORM_STRENGTH_MIN = 0.000
HERO_DEFORM_STRENGTH_MAX = 0.185 if FINAL_FOR_YOUTUBE else 0.135
HERO_DEFORM_DETAIL_STRENGTH_MAX = 0.072 if FINAL_FOR_YOUTUBE else 0.052
HERO_DEFORM_WAVE_HEIGHT_MAX = 0.115 if FINAL_FOR_YOUTUBE else 0.080
HERO_DEFORM_MAIN_DIM_FACTOR = 0.105 if FINAL_FOR_YOUTUBE else 0.085
HERO_DEFORM_DETAIL_DIM_FACTOR = 0.040 if FINAL_FOR_YOUTUBE else 0.030
HERO_DEFORM_WAVE_DIM_FACTOR = 0.070 if FINAL_FOR_YOUTUBE else 0.052
HERO_DEFORM_TWIST_MAX = math.radians(16.0 if FINAL_FOR_YOUTUBE else 11.0)
HERO_DEFORM_SUBDIV_VIEW = 1
HERO_DEFORM_SUBDIV_RENDER = 2 if FINAL_FOR_YOUTUBE else 1
HERO_DEFORM_NOISE_SIZE = 0.92
HERO_DEFORM_DETAIL_NOISE_SIZE = 0.46
HERO_DEFORM_NOISE_CONTRAST = 3.60
HERO_DEFORM_CONTROLLER_RADIUS = 0.42
HERO_DEFORM_CONTROLLER_Z = PRIMARY_BASE_Z + 1.15
HERO_DEFORM_KEYFRAME_STEP = 2

USE_HERO_MATERIAL_AUDIO_NODES = True
HERO_MATERIAL_EMISSION_MIN = 0.10
HERO_MATERIAL_EMISSION_MAX = 0.68 if FINAL_FOR_YOUTUBE else 0.52
HERO_MATERIAL_SELF_LIGHT_MIN = 0.018
HERO_MATERIAL_SELF_LIGHT_MAX = 0.34 if FINAL_FOR_YOUTUBE else 0.26
HERO_MATERIAL_BUMP_MIN = 0.010
HERO_MATERIAL_BUMP_MAX = 0.088 if FINAL_FOR_YOUTUBE else 0.065
HERO_MATERIAL_ROUGHNESS_MIN = 0.20
HERO_MATERIAL_ROUGHNESS_MAX = 0.58
HERO_MATERIAL_NOISE_SCALE_MIN = 4.0
HERO_MATERIAL_NOISE_SCALE_MAX = 13.5
HERO_MATERIAL_MAPPING_DRIFT = 0.18

# ============================================================
# CAMERA
# ============================================================
CAMERA_BASE_LOCATION = (0.0, -11.5, 5.6)
CAMERA_BASE_LENS = 34
CAMERA_DOF_FSTOP = 3.8 if FINAL_FOR_YOUTUBE else 6.5

CAMERA_BEAT_BUMP_Z = 0.08
CAMERA_BEAT_BUMP_Y = 0.10
CAMERA_ORBIT_AMOUNT = 0.32
CAMERA_PUSH_AMOUNT = 0.45
CAMERA_VERTICAL_SWAY = 0.35

# ============================================================
# LIGHTS
# ============================================================
LIGHT_ENERGY_MIN = 125.0
LIGHT_ENERGY_MAX = 158.0 if FINAL_FOR_YOUTUBE else 142.0
PHYSICS_ACCENT_EMISSION_MIN = 0.14
PHYSICS_ACCENT_EMISSION_MAX = 1.32 if FINAL_FOR_YOUTUBE else 1.05
PHYSICS_ACCENT_MIX_MIN = 0.20
PHYSICS_ACCENT_MIX_MAX = 0.68 if FINAL_FOR_YOUTUBE else 0.55

# ============================================================
# FORCE FIELDS
# ============================================================
FIELD_STRENGTH_MIN = 0.0
FIELD_STRENGTH_MAX = 42.0
HERO_GRAVITY_STRENGTH_MIN = 5.0
HERO_GRAVITY_STRENGTH_MAX = 34.0

TURB_STRENGTH_MIN = 0.25
TURB_STRENGTH_MAX = 4.8

VORTEX_STRENGTH_MIN = 0.15
VORTEX_STRENGTH_MAX = 2.6

# ============================================================
# MIST
# ============================================================
MIST_FLOAT_AMPLITUDE = 0.18
MIST_BEAT_BOOST = 0.06

# ============================================================
# PALETTE
# ============================================================
PEACE_PALETTE = {
    "twilight_blue": (0.020, 0.032, 0.060, 1.0),
    "soft_teal": (0.170, 0.460, 0.480, 1.0),
    "muted_gold": (0.720, 0.620, 0.340, 1.0),
    "dust_rose": (0.500, 0.300, 0.340, 1.0),
    "warm_white": (0.940, 0.930, 0.900, 1.0),
}

PALETTE_LIST = [
    PEACE_PALETTE["soft_teal"],
    PEACE_PALETTE["muted_gold"],
    PEACE_PALETTE["dust_rose"],
    PEACE_PALETTE["warm_white"],
]
