from __future__ import annotations

from .analyzer import analyze
from .apply import safe_apply_sections
from .cli import main, parse_args
from .common import (
    DEFAULT_MARKDOWN,
    DEFAULT_OUTPUT,
    DENY_PREFIXES,
    DENY_SUFFIXES,
    INTEGRATED_STATUSES,
    SAFE_PREFIXES,
    normalize_target,
    read_text,
    repo_rel,
    target_error,
    write_json,
    write_text,
)
from .sections import (
    added_line_ratio,
    analyze_section,
    code_block,
    declared_empty_code_product,
    document_metadata_int,
    document_metadata_value,
    metadata_value,
    new_file_payload_content,
    normalized_text,
    payload_truncated,
    run_git_apply_check,
    split_sections,
    summarize_sections,
    truncated_prefix,
)

__all__ = [
    "DEFAULT_MARKDOWN",
    "DEFAULT_OUTPUT",
    "DENY_PREFIXES",
    "DENY_SUFFIXES",
    "INTEGRATED_STATUSES",
    "SAFE_PREFIXES",
    "added_line_ratio",
    "analyze",
    "analyze_section",
    "code_block",
    "declared_empty_code_product",
    "document_metadata_int",
    "document_metadata_value",
    "main",
    "metadata_value",
    "new_file_payload_content",
    "normalize_target",
    "normalized_text",
    "parse_args",
    "payload_truncated",
    "read_text",
    "repo_rel",
    "run_git_apply_check",
    "safe_apply_sections",
    "split_sections",
    "summarize_sections",
    "target_error",
    "truncated_prefix",
    "write_json",
    "write_text",
]
