# This file is dot-sourced by run_unified_local_ai_refactor.ps1.
# Source lines: 652-1162.


function Write-ProviderWorkloadReportsFromProbe {
    param(
        [string]$ProbeReport,
        [string]$OllamaReport,
        [string]$NpuReport
    )

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OllamaReport) | Out-Null

    if (-not (Test-Path -LiteralPath $ProbeReport -PathType Leaf)) {
        throw "Provider probe report missing: $ProbeReport"
    }

    $Probe = Get-Content -LiteralPath $ProbeReport -Raw | ConvertFrom-Json
    $Ollama = @($Probe.lane_reports | Where-Object { $_.lane -eq "ollama" } | Select-Object -First 1)
    $Npu = @($Probe.lane_reports | Where-Object { $_.lane -eq "npu" } | Select-Object -First 1)

    if ($Ollama.Count -gt 0 -and [bool](Get-OptionalPropertyValue -Object $Ollama[0] -Name "passed" -Default $false)) {
        $OllamaLines = @(
            "# Ollama GPU Real Workload Report",
            "",
            "Generated by unified launcher from explicit provider probe.",
            "Lane: ollama",
            "Provider: Ollama",
            "Compute lane: GPU/CUDA",
            "Intended role: primary advisory only after workload quality routing passes.",
            ("Provider execution performed: {0}" -f (Get-OptionalPropertyValue -Object $Ollama[0] -Name "provider_execution_performed" -Default $false)),
            ("Probe passed: {0}" -f (Get-OptionalPropertyValue -Object $Ollama[0] -Name "passed" -Default $false)),
            ("Selected model: {0}" -f (Get-OptionalPropertyValue -Object $Ollama[0] -Name "selected_model" -Default "")),
            "",
            "Captured text preview:",
            ("{0}" -f (Get-OptionalPropertyValue -Object $Ollama[0] -Name "text_preview" -Default "")),
            "",
            "This report wraps a real provider probe result for workload quality routing.",
            "No patches, source writes, Blender or FFmpeg execution are performed by this report."
        )
        $OllamaLines | Set-Content -LiteralPath $OllamaReport -Encoding UTF8
    } else {
        Write-Warning "Ollama probe did not pass; Ollama workload report not written."
        if (Test-Path -LiteralPath $OllamaReport -PathType Leaf) {
            Remove-Item -LiteralPath $OllamaReport -Force
        }
    }

    if ($Npu.Count -gt 0) {
        $NpuLines = @(
            "# NPU OpenVINO Real Workload Report",
            "",
            "Generated by unified launcher from explicit provider probe.",
            "Lane: npu",
            "Provider: OpenVINO NPU",
            "Compute lane: NPU",
            "Intended role: probe, guardrail, decode diagnostic or knowledge-broker support.",
            "This lane is not promoted to primary advisory by this report.",
            ("Provider execution performed: {0}" -f (Get-OptionalPropertyValue -Object $Npu[0] -Name "provider_execution_performed" -Default $false)),
            ("Probe passed: {0}" -f (Get-OptionalPropertyValue -Object $Npu[0] -Name "passed" -Default $false)),
            ("Probe error: {0}" -f (Get-OptionalPropertyValue -Object $Npu[0] -Name "error" -Default "")),
            "",
            "Captured raw preview:",
            ("{0}" -f (Get-OptionalPropertyValue -Object $Npu[0] -Name "raw_preview" -Default "")),
            "",
            "This report wraps a real NPU probe result for workload quality routing.",
            "No patches, source writes, Blender or FFmpeg execution are performed by this report."
        )
        $NpuLines | Set-Content -LiteralPath $NpuReport -Encoding UTF8
    } else {
        Write-Warning "NPU probe entry missing; NPU workload report not written."
        if (Test-Path -LiteralPath $NpuReport -PathType Leaf) {
            Remove-Item -LiteralPath $NpuReport -Force
        }
    }
}


# IA_CARMINE_EXECUTION_TAIL_PATCH_BEGIN
$Script:UnifiedLauncherTranscriptPath = $null
$Script:UnifiedLauncherTranscriptStarted = $false
$Script:UnifiedLauncherExecutionTailWritten = $false

function Start-UnifiedLauncherExecutionTranscript {
    param(
        [string]$StampValue,
        [string]$Root,
        [bool]$ProdMode
    )

    if ($ProdMode) {
        Write-Host "[INFO] Prod mode: unified launcher debug transcript/tail evidence disabled."
        return
    }

    if ($Script:UnifiedLauncherTranscriptStarted) {
        return
    }

    $safeStamp = $StampValue
    if ([string]::IsNullOrWhiteSpace($safeStamp)) {
        $safeStamp = Get-Date -Format "yyyyMMdd-HHmmss"
    }

    $transcriptOutputDir = "output"
    if (-not [string]::IsNullOrWhiteSpace($Script:UnifiedLauncherOutputDir)) {
        $transcriptOutputDir = $Script:UnifiedLauncherOutputDir
    }
    $transcriptDir = Join-Path $Root (Join-Path $transcriptOutputDir ("local_ai_runs/{0}_unified_launcher_transcript" -f $safeStamp))
    $transcriptPath = Join-Path $transcriptDir ("unified_launcher_console_{0}.log" -f $safeStamp)

    try {
        New-Item -ItemType Directory -Force -Path $transcriptDir | Out-Null
        Start-Transcript -Path $transcriptPath -Force | Out-Null
        $Script:UnifiedLauncherTranscriptPath = $transcriptPath
        $Script:UnifiedLauncherTranscriptStarted = $true
        Write-Host "[INFO] Unified launcher transcript: $transcriptPath"
    } catch {
        Write-Warning ("Could not start unified launcher transcript: {0}" -f $_.Exception.Message)
        $Script:UnifiedLauncherTranscriptPath = $null
        $Script:UnifiedLauncherTranscriptStarted = $false
    }
}

function Write-UnifiedLauncherExecutionTailEvidence {
    param(
        [string]$StampValue,
        [string]$Root,
        [string]$RunDirValue,
        [string]$ManifestPathValue,
        [string[]]$ResolvedModesValue,
        [string[]]$ReportFilesValue,
        [string[]]$ContextFilesValue,
        [bool]$ProviderExecutionRequested,
        [bool]$PatchSpecsRequested,
        [bool]$ProdMode,
        [string]$FailureMessage = ""
    )

    if ($ProdMode) {
        Write-Host "[INFO] Prod mode: unified launcher execution-tail evidence disabled."
        return
    }

    if ($Script:UnifiedLauncherExecutionTailWritten) {
        Write-Host "[INFO] Unified launcher execution-tail evidence already written."
        return
    }

    if ($Script:UnifiedLauncherTranscriptStarted) {
        try {
            Stop-Transcript | Out-Null
        } catch {
            Write-Warning ("Could not stop unified launcher transcript: {0}" -f $_.Exception.Message)
        }
        $Script:UnifiedLauncherTranscriptStarted = $false
    }

    if ([string]::IsNullOrWhiteSpace($Script:UnifiedLauncherTranscriptPath)) {
        Write-Warning "Unified launcher transcript path is empty; execution-tail evidence not written."
        return
    }

    if (-not (Test-Path -LiteralPath $Script:UnifiedLauncherTranscriptPath -PathType Leaf)) {
        Write-Warning ("Unified launcher transcript is missing; execution-tail evidence not written: {0}" -f $Script:UnifiedLauncherTranscriptPath)
        return
    }

    $safeStamp = $StampValue
    if ([string]::IsNullOrWhiteSpace($safeStamp)) {
        $safeStamp = Get-Date -Format "yyyyMMdd-HHmmss"
    }

    $allLines = @(Get-Content -LiteralPath $Script:UnifiedLauncherTranscriptPath -Encoding UTF8 -ErrorAction SilentlyContinue)
    $tailLineCount = [Math]::Min(220, $allLines.Count)
    $tailLines = @($allLines | Select-Object -Last $tailLineCount)

    $warningLines = @($allLines | Where-Object {
        $_ -match "AVVISO|WARNING|Warning|failed with exit code|Fatal|fatal|Passed: False|Patch plan count: 0|provider.*failed|did not pass"
    } | Select-Object -Last 80)

    $evidenceDirRelative = "docs/LOCAL_VALIDATION_EVIDENCE"
    if (-not [string]::IsNullOrWhiteSpace($Script:UnifiedLauncherEvidenceDir)) {
        $evidenceDirRelative = $Script:UnifiedLauncherEvidenceDir
    }
    $evidenceDir = Join-Path $Root $evidenceDirRelative
    New-Item -ItemType Directory -Force -Path $evidenceDir | Out-Null

    $jsonPath = Join-Path $evidenceDir ("unified_launcher_execution_tail_{0}.json" -f $safeStamp)
    $mdPath = Join-Path $evidenceDir ("unified_launcher_execution_tail_{0}.md" -f $safeStamp)

    $normalizedTranscriptPath = $Script:UnifiedLauncherTranscriptPath.Replace('\', '/')

    $report = [ordered]@{
        schema_version = 1
        kind = "unified_launcher_execution_tail"
        generated_at = (Get-Date).ToString("o")
        stamp = $safeStamp
        passed = [string]::IsNullOrWhiteSpace($FailureMessage)
        prod_mode = $false
        debug_tail_enabled = $true
        provider_execution_requested = $ProviderExecutionRequested
        patch_specs_requested = $PatchSpecsRequested
        patch_application_performed = $false
        source_writes_performed = $false
        blender_runtime_execution_performed = $false
        ffmpeg_execution_performed = $false
        run_dir = $RunDirValue
        manifest = $ManifestPathValue
        transcript_path = $normalizedTranscriptPath
        transcript_line_count = $allLines.Count
        tail_line_count = $tailLineCount
        anomaly_line_count = $warningLines.Count
        failure_message = $FailureMessage
        resolved_modes = @($ResolvedModesValue)
        report_files = @($ReportFilesValue)
        context_files = @($ContextFilesValue)
        anomaly_lines = @($warningLines)
        tail = @($tailLines)
        errors = @()
        warnings = @()
    }

    ($report | ConvertTo-Json -Depth 8) | Set-Content -LiteralPath $jsonPath -Encoding UTF8

    $mdLines = New-Object System.Collections.Generic.List[string]
    [void]$mdLines.Add("# Unified launcher execution tail")
    [void]$mdLines.Add("")
    [void]$mdLines.Add(('- Stamp: `{0}`' -f $safeStamp))
    [void]$mdLines.Add('- Prod mode: `False`')
    [void]$mdLines.Add('- Debug tail enabled: `True`')
    [void]$mdLines.Add(('- Provider execution requested: `{0}`' -f $ProviderExecutionRequested))
    [void]$mdLines.Add(('- Patch specs requested: `{0}`' -f $PatchSpecsRequested))
    [void]$mdLines.Add(('- Transcript: `{0}`' -f $normalizedTranscriptPath))
    [void]$mdLines.Add(('- Transcript line count: `{0}`' -f $allLines.Count))
    [void]$mdLines.Add(('- Tail line count: `{0}`' -f $tailLineCount))
    [void]$mdLines.Add(('- Anomaly line count: `{0}`' -f $warningLines.Count))
    if (-not [string]::IsNullOrWhiteSpace($FailureMessage)) { [void]$mdLines.Add(('- Failure message: `{0}`' -f $FailureMessage)) }
    [void]$mdLines.Add("")
    [void]$mdLines.Add("## Anomaly lines")
    [void]$mdLines.Add("")
    [void]$mdLines.Add('```text')
    foreach ($line in $warningLines) {
        [void]$mdLines.Add($line)
    }
    [void]$mdLines.Add('```')
    [void]$mdLines.Add("")
    [void]$mdLines.Add("## Tail")
    [void]$mdLines.Add("")
    [void]$mdLines.Add('```text')
    foreach ($line in $tailLines) {
        [void]$mdLines.Add($line)
    }
    [void]$mdLines.Add('```')
    $mdLines | Set-Content -LiteralPath $mdPath -Encoding UTF8

    $Script:UnifiedLauncherExecutionTailWritten = $true
    Write-Host "[OK] Execution tail evidence: $jsonPath"
    Write-Host "[OK] Execution tail markdown: $mdPath"
}
# IA_CARMINE_EXECUTION_TAIL_PATCH_END

Show-LauncherIntro
$RepoRoot = Resolve-RepoRoot
Set-Location $RepoRoot
$env:PYTHONPATH = $RepoRoot
$ResolvedPythonExe = Resolve-PythonExe -Requested $PythonExe -Root $RepoRoot

$RepoRootCanonical = (Resolve-Path -LiteralPath $RepoRoot).Path.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
$ResolvedPythonCanonical = (Resolve-Path -LiteralPath $ResolvedPythonExe).Path
$RequiredRepoPy = Join-Path $RepoRootCanonical ".venv\Scripts\python.exe"
$NormalizedRepoRoot = $RepoRootCanonical.Replace("\", "/").ToLowerInvariant()
$NormalizedResolvedPython = $ResolvedPythonCanonical.Replace("\", "/").ToLowerInvariant()

Write-Host "[PYTHON-GATE] Repository root: $RepoRootCanonical"
Write-Host "[PYTHON-GATE] Resolved Python: $ResolvedPythonCanonical"
Write-Host "[PYTHON-GATE] Required RepoPy: $RequiredRepoPy"

if (-not $NormalizedResolvedPython.StartsWith($NormalizedRepoRoot + "/")) {
    [Console]::Error.WriteLine("[PYTHON-GATE] Rejected non-repository Python: $ResolvedPythonCanonical")
    [Console]::Error.WriteLine("[PYTHON-GATE] Use RepoPy only: $RequiredRepoPy")
    [Console]::Error.WriteLine("[PYTHON-GATE] Set `$RepoPy = (Resolve-Path .\.venv\Scripts\python.exe).Path and pass -PythonExe `$RepoPy.")
    exit 2
}

if (Test-Path -LiteralPath $RequiredRepoPy -PathType Leaf) {
    $RequiredRepoPyCanonical = (Resolve-Path -LiteralPath $RequiredRepoPy).Path
    $NormalizedRequiredRepoPy = $RequiredRepoPyCanonical.Replace("\", "/").ToLowerInvariant()
    if ($NormalizedResolvedPython -ne $NormalizedRequiredRepoPy) {
        [Console]::Error.WriteLine("[PYTHON-GATE] Rejected repository Python that is not canonical RepoPy: $ResolvedPythonCanonical")
        [Console]::Error.WriteLine("[PYTHON-GATE] Canonical RepoPy required: $RequiredRepoPyCanonical")
        exit 2
    }
}

$env:IA_CARMINE_PYTHON = $ResolvedPythonCanonical
$env:PYTHONPATH = $RepoRootCanonical
Write-Host "[PYTHON-GATE] RepoPy accepted and exported to IA_CARMINE_PYTHON."
Write-Host "[INFO] PYTHONPATH: $env:PYTHONPATH"
Write-Host "[INFO] Python: $ResolvedPythonExe"

if ($Interactive -or @($Mode).Count -eq 0) { $ResolvedModes = @(Read-InteractiveModes) } else { $ResolvedModes = @(Normalize-ModeList $Mode) }
if (@($ResolvedModes).Count -eq 0) { throw "No modes selected. Use -Interactive or -Mode all." }

if ([string]::IsNullOrWhiteSpace($Stamp)) { $Stamp = Get-Date -Format "yyyyMMdd-HHmmss" }
$DataStamp = $Stamp
if ($PrepareReviewPr) {
    if ([string]::IsNullOrWhiteSpace($ReviewPrBranch)) {
        $ReviewPrBranch = "CARMINEai/full-run-$Stamp"
    }
    if ([string]::IsNullOrWhiteSpace($ReviewPrTitle)) {
        $ReviewPrTitle = "feat(ai): full-run patch suggestion review $Stamp"
    }
    if ([string]::IsNullOrWhiteSpace($ReviewPrCommitMessage)) {
        $ReviewPrCommitMessage = "feat(ai): prepare full-run patch suggestion review"
    }
}
# IA_CARMINE_OUTPUT_DIR_EVIDENCE_DIR_FALLBACK_BEGIN
if ([string]::IsNullOrWhiteSpace($OutputDir)) { $OutputDir = "output" }
if ([string]::IsNullOrWhiteSpace($EvidenceDir)) { $EvidenceDir = "docs/LOCAL_VALIDATION_EVIDENCE" }
