"""Provider governor policy."""
from __future__ import annotations

from typing import Any

from .constants import PERMIT_REQUIREMENTS


def requirement_state(name: str, passed: bool, reason: str) -> dict[str, Any]:
    return {"requirement": name, "passed": passed, "reason": reason}


def build_policy(
    operator_intent: bool,
    quality_gate: dict[str, Any],
    accelerator_control: dict[str, Any],
) -> dict[str, Any]:
    scheduler = accelerator_control.get("scheduler") or {}
    gpu_mind = accelerator_control.get("gpu_mind") or {}
    requirements = [
        requirement_state("operator_intent", operator_intent, "explicit -OperatorIntent is required"),
        requirement_state("quality_gate_passed", bool(quality_gate.get("passed")), "quality gate must pass"),
        requirement_state(
            "accelerator_scheduler_generation_blocked_pre_run",
            scheduler.get("generation_allowed") is False,
            "pre-run scheduler must keep generation disabled",
        ),
        requirement_state(
            "gpu_mind_requires_launcher",
            bool(gpu_mind.get("decision_policy", {}).get("requires_run_launcher")),
            "GPU mind must require explicit launcher",
        ),
        requirement_state("workload_quality_policy_available", True, "validator supports --report-dir"),
        requirement_state("npu_audit_plan_available", True, "NPU audit plan is generated by governor"),
        requirement_state("gpu0_guardrail_available", True, "GPU.0 guardrail is generated by governor"),
    ]
    known = {item["requirement"] for item in requirements}
    missing = [name for name in PERMIT_REQUIREMENTS if name not in known]
    for name in missing:
        requirements.append(requirement_state(name, False, "requirement not produced"))
    return {
        "kind": "full0to10_provider_governor_policy",
        "passed": all(item["passed"] for item in requirements),
        "requirements": requirements,
        "operator_intent": operator_intent,
        "default_decision": "deny_until_all_requirements_pass",
    }
