<#
.SYNOPSIS
  Commit and push app-generated technical data to GitHub.

.DESCRIPTION
  This script is intended to be called by the local project application after it regenerates
  technical data such as AI indexes, manifests, compact JSON files, schema notes, or reports.

  It is intentionally conservative:
  - it only stages allowlisted paths by default;
  - it does not create an empty commit;
  - it prints the staged changes before committing;
  - it can run in dry-run mode;
  - it does not pull or rebase automatically unless explicitly requested.

.EXAMPLE
  .\Tools\git\auto_push_generated_data.ps1

.EXAMPLE
  .\Tools\git\auto_push_generated_data.ps1 -Message "chore: update app-generated technical data"

.EXAMPLE
  .\Tools\git\auto_push_generated_data.ps1 -DryRun
#>

param(
    [string]$RepoPath = ".",
    [string]$Branch = "master",
    [string]$Message = "chore: update app-generated technical data",
    [switch]$PullFirst,
    [switch]$DryRun,
    [switch]$IncludeOutputJson,
    [switch]$IncludeDocs,
    [switch]$IncludeAllGenerated
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Text)
    Write-Host "[auto-push] $Text"
}

function Invoke-Git {
    param(
        [Parameter(Mandatory=$true)][string[]]$Args,
        [switch]$AllowFailure
    )

    & git @Args
    $code = $LASTEXITCODE
    if ($code -ne 0 -and -not $AllowFailure) {
        throw "git $($Args -join ' ') failed with exit code $code"
    }
    return $code
}

$root = Resolve-Path $RepoPath
Write-Step "Repository: $root"

Push-Location $root
try {
    Invoke-Git @("rev-parse", "--is-inside-work-tree") | Out-Null

    $currentBranch = (& git branch --show-current).Trim()
    if ($currentBranch -ne $Branch) {
        throw "Current branch is '$currentBranch', expected '$Branch'. Stop to avoid pushing the wrong branch."
    }

    if ($PullFirst) {
        Write-Step "Pulling latest changes before staging."
        if (-not $DryRun) {
            Invoke-Git @("pull", "--ff-only", "origin", $Branch) | Out-Null
        }
    }

    $paths = New-Object System.Collections.Generic.List[string]

    # Primary app/index generated data.
    $paths.Add("indexAI")

    # NPU/context manifests generated by the project tools.
    $paths.Add("Tools/npu/*.json")
    $paths.Add("Tools/npu/*.md")

    # Optional broader generated data.
    if ($IncludeOutputJson -or $IncludeAllGenerated) {
        $paths.Add("output/*.json")
        $paths.Add("output/*.md")
        $paths.Add("output/*.txt")
    }

    if ($IncludeDocs -or $IncludeAllGenerated) {
        $paths.Add("docs")
    }

    Write-Step "Allowlisted paths to stage:"
    foreach ($p in $paths) {
        Write-Host "  - $p"
    }

    if ($DryRun) {
        Write-Step "Dry run: git status before staging."
        Invoke-Git @("status", "--short") | Out-Null
        Write-Step "Dry run complete. No changes staged, committed, or pushed."
        exit 0
    }

    foreach ($p in $paths) {
        Invoke-Git @("add", "--", $p) -AllowFailure | Out-Null
    }

    $staged = (& git diff --cached --name-only)
    if ([string]::IsNullOrWhiteSpace($staged)) {
        Write-Step "No staged generated-data changes found. Nothing to commit."
        exit 0
    }

    Write-Step "Staged files:"
    $staged -split "`n" | Where-Object { $_.Trim() } | ForEach-Object { Write-Host "  - $_" }

    Invoke-Git @("commit", "-m", $Message) | Out-Null
    Write-Step "Commit created."

    Invoke-Git @("push", "origin", $Branch) | Out-Null
    Write-Step "Pushed to origin/$Branch."
}
finally {
    Pop-Location
}
