#!/usr/bin/env python3
"""Validate selected semantic chunk bundles and produce compact evidence.

Report-only validator for bundles generated by Tools/ai/select_semantic_code_chunks.py.
It checks schema, budget, source-write/provider flags, duplicate chunk ids and
path guardrails. It may also emit compact evidence JSON/Markdown.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from report_utils import resolve_output_path, write_json_report
except ImportError:
    from Tools.validation.report_utils import resolve_output_path, write_json_report  # type: ignore

EXPECTED_KIND = "semantic_code_chunk_selection"
REPORT_KIND = "selected_semantic_chunks_validation"
EVIDENCE_KIND = "selected_semantic_chunks_evidence"
FORBIDDEN_PREFIXES = (
    ".git/",
    ".venv/",
    "__pycache__/",
    "indexAI/agent_memory/",
    "output/patch_specs/",
    "renders/",
    "venv/",
    "Scripting/ready_to_jazz_wow_youtube_profiles_audio_sync/",
)
FORBIDDEN_EXACT = {"Scripting/shared/blender_compat.py"}
FORBIDDEN_FRAGMENTS = ("full_analysis", "analysis_full")
REQUIRED_TOP_FIELDS = (
    "schema_version",
    "kind",
    "query",
    "source_chunks",
    "max_chunks",
    "max_total_chars",
    "selected_count",
    "total_selected_chars",
    "source_writes_performed",
    "provider_execution_performed",
    "passed",
    "errors",
    "warnings",
    "selected_chunks",
)
REQUIRED_CHUNK_FIELDS = (
    "chunk_id",
    "path",
    "symbol",
    "line_start",
    "line_end",
    "domain",
    "risk",
    "do_not_change",
    "sha256",
    "score",
    "matched_terms",
)


def repo_relative(path: Path, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def resolve_repo_path(repo_root: Path, raw: str) -> Path:
    path = Path(raw)
    return path.resolve() if path.is_absolute() else (repo_root / path).resolve()


def normalize_path(value: Any) -> str:
    return str(value or "").strip().replace("\\", "/")


def read_json_object(path: Path) -> tuple[dict[str, Any] | None, str | None]:
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError as exc:
        return None, f"invalid JSON at line {exc.lineno}, column {exc.colno}: {exc.msg}"
    except OSError as exc:
        return None, str(exc)
    if not isinstance(data, dict):
        return None, f"expected JSON object, got {type(data).__name__}"
    return data, None


def path_errors(path: str) -> list[str]:
    errors: list[str] = []
    normalized = normalize_path(path)
    if not normalized:
        return ["path is empty"]
    if Path(normalized).is_absolute():
        errors.append("absolute paths are not allowed")
    if normalized in FORBIDDEN_EXACT:
        errors.append(f"forbidden exact path: {normalized}")
    if any(normalized.startswith(prefix) for prefix in FORBIDDEN_PREFIXES):
        errors.append(f"forbidden path prefix: {normalized}")
    lower = normalized.lower()
    if any(fragment in lower for fragment in FORBIDDEN_FRAGMENTS) and lower.endswith(".json"):
        errors.append(f"forbidden analysis JSON path: {normalized}")
    if "*" in normalized or normalized.endswith("/"):
        errors.append("selected chunk paths must be concrete files")
    return errors


def validate_chunk(chunk: Any, index: int) -> dict[str, Any]:
    label = f"selected_chunks[{index}]"
    errors: list[str] = []
    warnings: list[str] = []
    if not isinstance(chunk, dict):
        return {"label": label, "path": label, "ok": False, "errors": [f"{label} must be an object"], "warnings": []}

    missing = [field for field in REQUIRED_CHUNK_FIELDS if field not in chunk]
    if missing:
        errors.append(f"missing required fields: {', '.join(missing)}")
    path = normalize_path(chunk.get("path"))
    errors.extend(path_errors(path))

    start = chunk.get("line_start")
    end = chunk.get("line_end")
    if not isinstance(start, int) or start <= 0:
        errors.append("line_start must be a positive integer")
    if not isinstance(end, int) or end <= 0:
        errors.append("line_end must be a positive integer")
    if isinstance(start, int) and isinstance(end, int) and end < start:
        errors.append("line_end must be >= line_start")
    if not isinstance(chunk.get("domain"), list):
        errors.append("domain must be a list")
    if not isinstance(chunk.get("matched_terms"), list):
        errors.append("matched_terms must be a list")
    if not isinstance(chunk.get("do_not_change"), bool):
        errors.append("do_not_change must be a boolean")
    if not isinstance(chunk.get("score"), int) or int(chunk.get("score") or 0) <= 0:
        errors.append("score must be a positive integer")
    if chunk.get("do_not_change") is True:
        warnings.append("chunk is marked do_not_change and must remain advisory-only")

    return {
        "label": label,
        "path": path,
        "chunk_id": chunk.get("chunk_id"),
        "symbol": chunk.get("symbol"),
        "score": chunk.get("score"),
        "risk": chunk.get("risk"),
        "do_not_change": chunk.get("do_not_change"),
        "ok": not errors,
        "errors": errors,
        "warnings": warnings,
    }


def validate_bundle(repo_root: Path, bundle_path: Path, max_total_chars: int | None) -> dict[str, Any]:
    rel_path = repo_relative(bundle_path, repo_root)
    errors: list[str] = []
    warnings: list[str] = []
    data, parse_error = read_json_object(bundle_path)
    if parse_error or data is None:
        return {"path": rel_path, "exists": bundle_path.exists(), "json_ok": False, "kind": None, "ok": False, "errors": [parse_error or "unknown JSON parse error"], "warnings": [], "selected_count": 0, "total_selected_chars": 0, "chunk_checks": []}

    missing = [field for field in REQUIRED_TOP_FIELDS if field not in data]
    if missing:
        errors.append(f"missing required fields: {', '.join(missing)}")
    if data.get("schema_version") != 1:
        errors.append("schema_version must be 1")
    if data.get("kind") != EXPECTED_KIND:
        errors.append(f"kind must be {EXPECTED_KIND}")
    if data.get("passed") is not True:
        errors.append("selected chunks passed must be true")
    if data.get("source_writes_performed") is not False:
        errors.append("source_writes_performed must be false")
    if data.get("provider_execution_performed") is not False:
        errors.append("provider_execution_performed must be false")
    if not isinstance(data.get("errors"), list) or data.get("errors"):
        errors.append("errors must be an empty list")
    if not isinstance(data.get("warnings"), list):
        errors.append("warnings must be a list")

    max_chunks = data.get("max_chunks")
    selected_count = data.get("selected_count")
    total_chars = data.get("total_selected_chars")
    declared_budget = data.get("max_total_chars")
    if not isinstance(max_chunks, int) or max_chunks <= 0:
        errors.append("max_chunks must be a positive integer")
    if not isinstance(selected_count, int) or selected_count <= 0:
        errors.append("selected_count must be a positive integer")
    if not isinstance(total_chars, int) or total_chars <= 0:
        errors.append("total_selected_chars must be a positive integer")
    if isinstance(max_chunks, int) and isinstance(selected_count, int) and selected_count > max_chunks:
        errors.append("selected_count exceeds max_chunks")
    if isinstance(total_chars, int) and isinstance(declared_budget, int) and total_chars > declared_budget:
        errors.append("total_selected_chars exceeds declared max_total_chars")
    if max_total_chars is not None and isinstance(total_chars, int) and total_chars > max_total_chars:
        errors.append(f"total_selected_chars exceeds validator max_total_chars {max_total_chars}")

    chunks = data.get("selected_chunks")
    if not isinstance(chunks, list) or not chunks:
        errors.append("selected_chunks must be a non-empty list")
        chunk_checks: list[dict[str, Any]] = []
    else:
        chunk_checks = [validate_chunk(chunk, index) for index, chunk in enumerate(chunks)]
        if isinstance(selected_count, int) and selected_count != len(chunks):
            errors.append("selected_count does not match selected_chunks length")
        seen_ids: set[str] = set()
        for check in chunk_checks:
            cid = str(check.get("chunk_id") or "")
            if cid in seen_ids:
                errors.append(f"duplicate chunk_id: {cid}")
            seen_ids.add(cid)
            for error in check.get("errors", []):
                errors.append(f"{check.get('path')}: {error}")
            for warning in check.get("warnings", []):
                warnings.append(f"{check.get('path')}: {warning}")

    return {
        "path": rel_path,
        "exists": True,
        "json_ok": True,
        "kind": data.get("kind"),
        "ok": not errors,
        "errors": errors,
        "warnings": warnings,
        "query": data.get("query"),
        "selected_count": selected_count if isinstance(selected_count, int) else 0,
        "total_selected_chars": total_chars if isinstance(total_chars, int) else 0,
        "max_chunks": max_chunks if isinstance(max_chunks, int) else 0,
        "max_total_chars": declared_budget if isinstance(declared_budget, int) else 0,
        "source_chunks": normalize_path(data.get("source_chunks")),
        "chunk_checks": chunk_checks,
    }


def evidence_markdown(evidence: dict[str, Any]) -> str:
    lines = [
        "# Selected Semantic Chunks Evidence",
        "",
        f"- Passed: `{evidence['passed']}`",
        f"- Bundle: `{evidence['source_bundle']}`",
        f"- Selected count: `{evidence['selected_count']}`",
        f"- Total selected chars: `{evidence['total_selected_chars']}`",
        f"- Provider execution performed: `{evidence['provider_execution_performed']}`",
        f"- Source writes performed: `{evidence['source_writes_performed']}`",
        "",
        "## Decision",
        "",
    ]
    for key, value in evidence.get("decision", {}).items():
        lines.append(f"- `{key}`: `{value}`")
    if evidence.get("warnings"):
        lines.extend(["", "## Warnings", ""])
        for warning in evidence["warnings"]:
            lines.append(f"- {warning}")
    if evidence.get("errors"):
        lines.extend(["", "## Errors", ""])
        for error in evidence["errors"]:
            lines.append(f"- {error}")
    return "\n".join(lines).rstrip() + "\n"


def build_evidence(report: dict[str, Any], repo_root: Path, bundle_path: Path) -> dict[str, Any]:
    check = report["results"][0] if report.get("results") else {}
    errors = report.get("errors", [])
    return {
        "schema_version": 1,
        "kind": EVIDENCE_KIND,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "repo_root": repo_root.as_posix(),
        "source_bundle": repo_relative(bundle_path, repo_root),
        "passed": report["passed"],
        "errors": errors,
        "warnings": report.get("warnings", []),
        "provider_execution_performed": False,
        "source_writes_performed": False,
        "selected_count": check.get("selected_count", 0),
        "total_selected_chars": check.get("total_selected_chars", 0),
        "max_chunks": check.get("max_chunks", 0),
        "max_total_chars": check.get("max_total_chars", 0),
        "source_chunks": check.get("source_chunks", ""),
        "decision": {
            "selected_chunks_built": bool(check.get("selected_count", 0) > 0),
            "budget_respected": not any("exceeds" in str(err) for err in errors),
            "provider_execution_seen": False,
            "source_writes_performed": False,
            "forbidden_paths_blocked": not any("forbidden" in str(err) for err in errors),
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--bundle", required=True)
    parser.add_argument("--output")
    parser.add_argument("--evidence-output")
    parser.add_argument("--markdown-output")
    parser.add_argument("--max-total-chars", type=int, default=None)
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    bundle_path = resolve_repo_path(repo_root, args.bundle)
    result = validate_bundle(repo_root, bundle_path, args.max_total_chars)
    errors = [f"{result['path']}: {error}" for error in result.get("errors", [])]
    warnings = [f"{result['path']}: {warning}" for warning in result.get("warnings", [])]
    report = {
        "schema_version": 1,
        "kind": REPORT_KIND,
        "repo_root": repo_root.as_posix(),
        "passed": not errors,
        "errors": errors,
        "warnings": warnings,
        "results": [result],
    }

    output = resolve_output_path(repo_root, args.output) if args.output else None
    print(write_json_report(report, output), end="")

    if args.evidence_output or args.markdown_output:
        evidence = build_evidence(report, repo_root, bundle_path)
        if args.evidence_output:
            evidence_path = resolve_output_path(repo_root, args.evidence_output)
            evidence_path.parent.mkdir(parents=True, exist_ok=True)
            evidence_path.write_text(json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        if args.markdown_output:
            markdown_path = resolve_output_path(repo_root, args.markdown_output)
            markdown_path.parent.mkdir(parents=True, exist_ok=True)
            markdown_path.write_text(evidence_markdown(evidence), encoding="utf-8")

    return 0 if report["passed"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
