"""Central dispatcher for validators, smokes, and validation gates.

Use ``python -m Tools.validation <tool> ...`` instead of launching validation
scripts by file path. Packaged validations resolve to their package CLIs;
remaining maintained tools fall back to ``Tools.validation.<tool>:main``.
"""

from pathlib import Path

from Tools.tool_dispatch import ToolDispatcher

TOOL_MAIN_TARGETS: dict[str, str] = {
    "check_ia_carmine_core_refactor_imports": "Tools.validation.core_refactor.import_compat_smoke.cli:main",
    "agent_review_patch_plan_full_validation": "Tools.validation.agent_review.patch_plan_full_validation.cli:main",
    "check_ai_context_pack_contract": "Tools.validation.agent_context.check_ai_context_pack_contract.cli:main",
    "check_ai_dry_run_matrix_cases": "Tools.validation.pipeline.dry_run_matrix_cases.cli:main",
    "check_ai_dry_run_matrix_contract": "Tools.validation.pipeline.dry_run_matrix_contract.cli:main",
    "check_ai_dry_run_matrix_outputs": "Tools.validation.pipeline.dry_run_matrix_outputs.cli:main",
    "check_ai_pipeline_modules": "Tools.validation.pipeline.ai_pipeline_modules.cli:main",
    "check_ai_pipeline_report_contract": "Tools.validation.pipeline.ai_pipeline_report_contract.cli:main",
    "check_ai_workload_report_quality": "Tools.validation.ai_workload.report_quality.cli:main",
    "check_dry_run_matrix_evidence_bundle": "Tools.validation.pipeline.dry_run_matrix_evidence_bundle.cli:main",
    "check_github_evidence_bundle": "Tools.validation.repository_product.github_evidence_bundle.cli:main",
    "check_gpu0_companion_contract": "Tools.validation.provider_mesh.gpu0_companion_contract.cli:main",
    "check_heap_exchange_runtime_lifecycle": "Tools.validation.heap_exchange.runtime_lifecycle_check.cli:main",
    "check_local_ai_adapter_manifest": "Tools.validation.pipeline.check_local_ai_adapter_manifest.cli:main",
    "check_markdown_line_limits": "Tools.validation.docs_hygiene.markdown_line_limits.cli:main",
    "check_md_code_coherence": "Tools.validation.docs_hygiene.md_code_coherence.cli:main",
    "check_npu_decode_quality_remediation": "Tools.validation.provider_mesh.npu_decode_quality_remediation.cli:main",
    "check_npu_knowledge_broker_packet": "Tools.validation.provider_mesh.npu_knowledge_broker_packet.cli:main",
    "check_npu_pipeline_docs": "Tools.validation.pipeline.npu_pipeline_docs.cli:main",
    "check_npu_pipeline_helper_tests": "Tools.validation.pipeline.npu_pipeline_helper_tests.cli:main",
    "check_openvino_peer_topology_contract": "Tools.validation.provider_mesh.openvino_peer_topology_contract.cli:main",
    "check_patch_spec_drafts": "Tools.validation.generated_patch_specs.patch_spec_drafts.cli:main",
    "check_patch_suggestion_product_separation": "Tools.validation.patch_product.product_separation.cli:main",
    "check_real_product_intrinsic_capability_contract": "Tools.validation.real_product.intrinsic_capability_contract.cli:main",
    "check_real_product_live_provider_gate": "Tools.validation.real_product.live_provider_gate.cli:main",
    "check_real_product_runtime_mesh_contract": "Tools.validation.real_product.runtime_mesh_contract.cli:main",
    "check_repository_change_proposals": "Tools.validation.repository_product.repository_change_proposals.cli:main",
    "check_review_pr_final_product_contract": "Tools.validation.repository_product.review_pr_final_product_contract.cli:main",
    "check_review_pr_product_readiness": "Tools.validation.repository_product.review_pr_product_readiness.cli:main",
    "check_unified_run_manifest_schema": "Tools.validation.runtime_universe.unified_run_manifest_schema.cli:main",
    "check_workflow_python_invocation_policy": "Tools.validation.workflow_run.python_invocation_policy.cli:main",
    "build_full_python_line_count_markdown": "Tools.validation.docs_hygiene.full_python_line_count_markdown.cli:main",
    "build_markdown_inventory": "Tools.validation.docs_hygiene.markdown_inventory.cli:main",
    "patch_notes_quality_product_smoke": "Tools.validation.patch_product.patch_notes_quality_product_smoke.cli:main",
    "npu_pipeline_modules_check": "Tools.validation.pipeline.npu_pipeline_modules_check.cli:main",
    "reviewed_patch_specs_check": "Tools.validation.generated_patch_specs.reviewed_patch_specs_check.cli:main",
    "run_agent_review_code_patch_plan_smoke": "Tools.validation.agent_review.code_patch_plan_smoke.cli:main",
    "run_agent_review_decision_loop_smoke": "Tools.validation.agent_review.decision_loop_smoke.cli:main",
    "run_agent_review_evidence_sufficiency_smoke": "Tools.validation.agent_review.evidence_sufficiency_smoke.cli:main",
    "run_agent_review_full_toolbox_workflow_static_smoke": "Tools.validation.agent_review.full_toolbox_workflow_static_smoke.cli:main",
    "run_agent_review_patch_bundle_builder_smoke": "Tools.validation.agent_review.patch_bundle_builder_smoke.cli:main",
    "run_agent_review_patch_plan_smoke": "Tools.validation.agent_review.patch_plan_smoke.cli:main",
    "run_agent_review_warning_policy_smoke": "Tools.validation.agent_review.warning_policy_smoke.cli:main",
    "run_agent_runtime_tool_broker_smoke": "Tools.validation.runtime_tool.agent_runtime_tool_broker_smoke.cli:main",
    "run_ai_workload_quality_report_dir_smoke": "Tools.validation.ai_workload.quality_report_dir_smoke.cli:main",
    "run_ai_workload_report_quality_stamp_scoped_smoke": "Tools.validation.ai_workload.report_quality_stamp_scoped_smoke.cli:main",
    "run_external_heap_postrun_provider_execution_smoke": "Tools.validation.external_heap.postrun_provider_execution_smoke.cli:main",
    "run_external_heap_provider_execution_detection_smoke": "Tools.validation.external_heap.provider_execution_detection_smoke.cli:main",
    "run_external_heap_revision_context_applicability_smoke": "Tools.validation.external_heap.revision_context_applicability_smoke.cli:main",
    "run_gpu_planner_json_contract_smoke": "Tools.validation.provider_mesh.gpu_planner_json_contract_smoke.cli:main",
    "run_gpu_runner_provider_error_smoke": "Tools.validation.provider_mesh.gpu_runner_provider_error_smoke.cli:main",
    "run_gpu_runtime_tool_bootstrap_smoke": "Tools.validation.runtime_tool.gpu_runtime_tool_bootstrap_smoke.cli:main",
    "run_heap_code_execution_tool_smoke": "Tools.validation.heap_runtime.code_execution_tool_smoke.cli:main",
    "run_heap_exchange_closure_audit_smoke": "Tools.validation.heap_exchange.closure_audit_smoke.cli:main",
    "run_heap_exchange_review_bridge_smoke": "Tools.validation.heap_exchange.review_bridge_smoke.cli:main",
    "run_heap_exchange_runtime_lifecycle_smoke": "Tools.validation.heap_exchange.runtime_lifecycle_smoke.cli:main",
    "run_heap_peer_runtime_chain_smoke": "Tools.validation.heap_exchange.peer_runtime_chain_smoke.cli:main",
    "run_heap_peer_runtime_manifest_smoke": "Tools.validation.heap_exchange.peer_runtime_manifest_smoke.cli:main",
    "run_heap_provider_budget_governor_smoke": "Tools.validation.heap_provider.budget_governor_smoke.cli:main",
    "run_heap_provider_invocation_contract_smoke": "Tools.validation.heap_provider.invocation_contract_smoke.cli:main",
    "run_heap_provider_peer_review_events_scope_smoke": "Tools.validation.heap_provider.peer_review_events_scope_smoke.cli:main",
    "run_heap_runtime_completeness_gate_smoke": "Tools.validation.heap_runtime.completeness_gate_smoke.cli:main",
    "run_provider_boot_gate_smoke": "Tools.validation.heap_runtime.provider_boot_gate_smoke.cli:main",
    "run_provider_loop_activation_smoke": "Tools.validation.heap_runtime.provider_loop_activation_smoke.cli:main",
    "run_heap_runtime_launcher_command_smoke": "Tools.validation.heap_runtime.launcher_command_smoke.cli:main",
    "run_heap_virtual_dev_environment_smoke": "Tools.validation.heap_runtime.virtual_dev_environment_smoke.cli:main",
    "run_md_split_dir_validator_smoke": "Tools.validation.docs_hygiene.md_split_dir_validator_smoke.cli:main",
    "run_npu_micro_task_companion_smoke": "Tools.validation.provider_mesh.npu_micro_task_companion_smoke.cli:main",
    "run_npu_runtime_tool_context_smoke": "Tools.validation.runtime_tool.npu_runtime_tool_context_smoke.cli:main",
    "run_npu_runtime_tool_execution_smoke": "Tools.validation.runtime_tool.npu_runtime_tool_execution_smoke.cli:main",
    "run_npu_runtime_tool_fallback_smoke": "Tools.validation.runtime_tool.npu_runtime_tool_fallback_smoke.cli:main",
    "run_npu_tool_request_contract_smoke": "Tools.validation.provider_mesh.npu_tool_request_contract_smoke.cli:main",
    "run_ollama_tool_gateway_smoke": "Tools.validation.provider_mesh.ollama_tool_gateway_smoke.cli:main",
    "run_ollama_sdk_adapter_smoke": "Tools.validation.provider_mesh.ollama_sdk_adapter_smoke.cli:main",
    "run_openvino_peer_topology_contract_smoke": "Tools.validation.provider_mesh.openvino_peer_topology_contract_smoke.cli:main",
    "run_operator_product_launcher_smoke": "Tools.validation.workflow_run.operator_product_launcher_smoke.cli:main",
    "run_orchestrator_direct_gpu_counter_smoke": "Tools.validation.provider_mesh.orchestrator_direct_gpu_counter_smoke.cli:main",
    "run_orchestrator_gpu_runtime_tool_routing_smoke": "Tools.validation.runtime_tool.orchestrator_gpu_runtime_tool_routing_smoke.cli:main",
    "run_generated_patch_specs_current_stamp_discovery_smoke": "Tools.validation.generated_patch_specs.current_stamp_discovery_smoke.cli:main",
    "run_generated_patch_specs_empty_product_smoke": "Tools.validation.generated_patch_specs.empty_product_smoke.cli:main",
    "run_generated_patch_specs_review_pr_lane_smoke": "Tools.validation.generated_patch_specs.review_pr_lane_smoke.cli:main",
    "run_patch_suggestion_bundle_apply_smoke": "Tools.validation.patch_product.patch_suggestion_bundle_apply_smoke.cli:main",
    "run_real_product_intrinsic_capability_contract_smoke": "Tools.validation.real_product.intrinsic_capability_contract_smoke.cli:main",
    "run_real_product_preflight_gate": "Tools.validation.real_product.preflight_gate.cli:main",
    "run_real_product_preflight_gate_smoke": "Tools.validation.real_product.preflight_gate_smoke.cli:main",
    "run_real_product_profile_smoke": "Tools.validation.real_product.profile_smoke.cli:main",
    "run_real_product_runtime_mesh_contract_smoke": "Tools.validation.real_product.runtime_mesh_contract_smoke.cli:main",
    "run_real_product_single_entry_exit_smoke": "Tools.validation.real_product.single_entry_exit_smoke.cli:main",
    "run_prepare_review_pr_auto_include_smoke": "Tools.validation.repository_product.prepare_review_pr_auto_include_smoke.cli:main",
    "run_prepare_review_pr_flag_smoke": "Tools.validation.repository_product.prepare_review_pr_flag_smoke.cli:main",
    "run_repository_change_proposals_runtime_evidence_smoke": "Tools.validation.repository_product.repository_change_proposals_runtime_evidence_smoke.cli:main",
    "run_repository_consistency_map_smoke": "Tools.validation.repository_product.repository_consistency_map_smoke.cli:main",
    "run_review_pr_final_product_contract_smoke": "Tools.validation.repository_product.review_pr_final_product_contract_smoke.cli:main",
    "run_review_pr_prepare_args_smoke": "Tools.validation.repository_product.review_pr_prepare_args_smoke.cli:main",
    "run_review_pr_product_readiness_smoke": "Tools.validation.repository_product.review_pr_product_readiness_smoke.cli:main",
    "run_repo_hygiene_plan_smoke": "Tools.validation.docs_hygiene.repo_hygiene_plan_smoke.cli:main",
    "run_runtime_evidence_correlation_launcher_wiring_smoke": "Tools.validation.workflow_run.runtime_evidence_correlation_launcher_wiring_smoke.cli:main",
    "run_runtime_tool_feedback_loop_smoke": "Tools.validation.runtime_tool.runtime_tool_feedback_loop_smoke.cli:main",
    "run_runtime_tool_guidance_fallback_smoke": "Tools.validation.runtime_tool.runtime_tool_guidance_fallback_smoke.cli:main",
    "run_runtime_universe_smoke": "Tools.validation.runtime_universe.runtime_universe_smoke.cli:main",
    "run_schema_repair_context_smoke": "Tools.validation.schema_repair.context_smoke.cli:main",
    "run_schema_repair_retry_bootstrap_smoke": "Tools.validation.schema_repair.retry_bootstrap_smoke.cli:main",
    "run_schema_repair_retry_smoke": "Tools.validation.schema_repair.retry_smoke.cli:main",
    "run_task_ingress_contract_smoke": "Tools.validation.heap_exchange.task_ingress_contract_smoke.cli:main",
    "run_task_patch_suggestion_markdown_authoring_smoke": "Tools.validation.patch_product.task_patch_suggestion_markdown_authoring_smoke.cli:main",
    "run_task_patch_suggestion_runtime_deferral_smoke": "Tools.validation.patch_product.task_patch_suggestion_runtime_deferral_smoke.cli:main",
    "run_unified_chain_contract_args_smoke": "Tools.validation.runtime_universe.unified_chain_contract_args_smoke.cli:main",
    "run_unified_chain_contract_smoke": "Tools.validation.runtime_universe.unified_chain_contract_smoke.cli:main",
    "run_unified_launcher_forbid_continue_on_validation_error_smoke": "Tools.validation.runtime_universe.unified_launcher_forbid_continue_on_validation_error_smoke.cli:main",
    "run_unified_manifest_runtime_evidence_correlation_smoke": "Tools.validation.runtime_universe.unified_manifest_runtime_evidence_correlation_smoke.cli:main",
    "run_unified_observer_extended_smoke": "Tools.validation.runtime_universe.unified_observer_extended_smoke.cli:main",
    "run_unified_run_manifest_schema_smoke": "Tools.validation.runtime_universe.unified_run_manifest_schema_smoke.cli:main",
    "run_unified_run_observer_smoke": "Tools.validation.runtime_universe.unified_run_observer_smoke.cli:main",
    "test_npu_pipeline_helpers": "Tools.validation.pipeline.test_npu_pipeline_helpers.cli:main",
    "unified_chain_contract": "Tools.validation.runtime_universe.unified_chain_contract.cli:main",
    "apply_docs_contract_drift_fixes": "Tools.validation.docs_hygiene.apply_docs_contract_drift_fixes.cli:main",
    "build_python_line_count_csv": "Tools.validation.docs_hygiene.build_python_line_count_csv.cli:main",
    "build_script_inventory": "Tools.validation.docs_hygiene.build_script_inventory.cli:main",
    "check_code_contract_drift": "Tools.validation.docs_hygiene.check_code_contract_drift.cli:main",
    "check_docs_contract_drift": "Tools.validation.docs_hygiene.check_docs_contract_drift.cli:main",
    "check_docs_links": "Tools.validation.docs_hygiene.check_docs_links.cli:main",
    "check_file_line_limits": "Tools.validation.docs_hygiene.check_file_line_limits.cli:main",
    "check_json_artifacts": "Tools.validation.docs_hygiene.check_json_artifacts.cli:main",
    "check_package_structure": "Tools.validation.docs_hygiene.check_package_structure.cli:main",
    "check_python_syntax": "Tools.validation.docs_hygiene.check_python_syntax.cli:main",
    "check_refactor_status_consistency": "Tools.validation.docs_hygiene.check_refactor_status_consistency.cli:main",
    "check_generated_artifact_path_policy": "Tools.validation.generated_artifacts.check_generated_artifact_path_policy.cli:main",
    "check_generated_blender_script_policy": "Tools.validation.generated_artifacts.check_generated_blender_script_policy.cli:main",
    "check_generated_python_policy": "Tools.validation.generated_artifacts.check_generated_python_policy.cli:main",
    "check_artifact_domain_registry": "Tools.validation.runtime_tool.check_artifact_domain_registry.cli:main",
    "check_blender_shared_compat_smoke": "Tools.validation.legacy_blender.check_blender_shared_compat_smoke.cli:main",
    "check_agent_memory_policy": "Tools.validation.agent_memory.check_agent_memory_policy.cli:main",
    "check_ai_model_json": "Tools.validation.pipeline.check_ai_model_json.cli:main",
    "check_core_activation_agnostic_contract": "Tools.validation.runtime_universe.check_core_activation_agnostic_contract.cli:main",
    "check_execution_plan_status": "Tools.validation.runtime_universe.check_execution_plan_status.cli:main",
    "check_full_context_golden_docs_contract": "Tools.validation.agent_context.check_full_context_golden_docs_contract.cli:main",
    "check_full_context_golden_proposals": "Tools.validation.agent_context.check_full_context_golden_proposals.cli:main",
    "check_full_run_bundle_completeness": "Tools.validation.real_product.check_full_run_bundle_completeness.cli:main",
    "check_local_ai_enrichment_plan": "Tools.validation.agent_context.check_local_ai_enrichment_plan.cli:main",
    "check_patchkit_bundle_contract": "Tools.validation.patch_product.check_patchkit_bundle_contract.cli:main",
    "check_provider_result_parsing": "Tools.validation.provider_mesh.check_provider_result_parsing.cli:main",
    "check_runtime_evidence_correlation": "Tools.validation.runtime_universe.check_runtime_evidence_correlation.cli:main",
    "check_runtime_hardware_delegation_contract": "Tools.validation.provider_mesh.check_runtime_hardware_delegation_contract.cli:main",
    "check_selected_semantic_chunks": "Tools.validation.agent_context.check_selected_semantic_chunks.cli:main",
    "check_selective_execution_plan": "Tools.validation.runtime_universe.check_selective_execution_plan.cli:main",
    "check_validation_report_contract": "Tools.validation.pipeline.check_validation_report_contract.cli:main",
    "run_agent_memory_routing_policy_smoke": "Tools.validation.agent_memory.run_agent_memory_routing_policy_smoke.cli:main",
    "run_agent_runtime_debug_lab_smoke": "Tools.validation.runtime_tool.run_agent_runtime_debug_lab_smoke.cli:main",
    "run_code_edit_proposal_smoke": "Tools.validation.patch_product.run_code_edit_proposal_smoke.cli:main",
    "run_code_product_artifact_intake_smoke": "Tools.validation.code_product.run_code_product_artifact_intake_smoke.cli:main",
    "run_core_runtime_guard_suite": "Tools.validation.runtime_universe.run_core_runtime_guard_suite.cli:main",
    "run_deterministic_recommendation_synthesizer_smoke": "Tools.validation.deterministic_recommendations.run_deterministic_recommendation_synthesizer_smoke.cli:main",
    "run_heap_file_backed_request_startup_smoke": "Tools.validation.heap_runtime.run_heap_file_backed_request_startup_smoke.cli:main",
    "run_heap_final_readable_product_smoke": "Tools.validation.heap_runtime.run_heap_final_readable_product_smoke.cli:main",
    "run_heap_gate_terminal_invariants_smoke": "Tools.validation.heap_runtime.run_heap_gate_terminal_invariants_smoke.cli:main",
    "run_heap_negative_preview_rewrite_contract_smoke": "Tools.validation.heap_runtime.run_heap_negative_preview_rewrite_contract_smoke.cli:main",
    "run_heap_source_allowlist_contract_smoke": "Tools.validation.heap_runtime.run_heap_source_allowlist_contract_smoke.cli:main",
    "run_heap_source_anchor_priority_smoke": "Tools.validation.heap_runtime.run_heap_source_anchor_priority_smoke.cli:main",
    "run_heap_startup_context_ingestion_smoke": "Tools.validation.heap_runtime.run_heap_startup_context_ingestion_smoke.cli:main",
    "run_observable_peer_activity_contract_smoke": "Tools.validation.provider_mesh.run_observable_peer_activity_contract_smoke.cli:main",
    "run_patch_candidate_synthesis_smoke": "Tools.validation.patch_product.run_patch_candidate_synthesis_smoke.cli:main",
    "run_patchkit_bundle_contract_smoke": "Tools.validation.patch_product.run_patchkit_bundle_contract_smoke.cli:main",
    "run_patchkit_smoke": "Tools.validation.patch_product.run_patchkit_smoke.cli:main",
    "run_provider_tool_evidence_chain_smoke": "Tools.validation.runtime_tool.run_provider_tool_evidence_chain_smoke.cli:main",
    "run_provider_tool_loop_smoke": "Tools.validation.runtime_tool.run_provider_tool_loop_smoke.cli:main",
    "run_refactor_duplication_audit_smoke": "Tools.validation.docs_hygiene.run_refactor_duplication_audit_smoke.cli:main",
    "run_runtime_evidence_correlation_smoke": "Tools.validation.runtime_universe.run_runtime_evidence_correlation_smoke.cli:main",
    "run_runtime_file_refs_smoke": "Tools.validation.runtime_tool.run_runtime_file_refs_smoke.cli:main",
    "run_runtime_heap_sqlite_sidecar_smoke": "Tools.validation.runtime_universe.run_runtime_heap_sqlite_sidecar_smoke.cli:main",
    "check_runtime_tool_broker_dispatch_alignment": "Tools.validation.runtime_tool.broker_dispatch_alignment.cli:main",
    "run_runtime_hardcode_guard_smoke": "Tools.validation.runtime_universe.run_runtime_hardcode_guard_smoke.cli:main",
    "run_runtime_sqlite_persistent_write_smoke": "Tools.validation.agent_memory.run_runtime_sqlite_persistent_write_smoke.cli:main",
    "run_shared_toolbox_ai_to_ai_bundle_smoke": "Tools.validation.agent_context.run_shared_toolbox_ai_to_ai_bundle_smoke.cli:main",
    "run_startup_check_cli_contract_smoke": "Tools.validation.workflow_run.run_startup_check_cli_contract_smoke.cli:main",
    "run_substantive_planning_smoke": "Tools.validation.agent_context.run_substantive_planning_smoke.cli:main",
    "test_composer_decision": "Tools.validation.heap_final_proposals.test_composer_decision.cli:main",
    "test_proposal_gate": "Tools.validation.heap_final_proposals.test_proposal_gate.cli:main",
}


def main(argv: list[str] | None = None) -> int:
    return ToolDispatcher(
        package="Tools.validation",
        package_dir=Path(__file__).resolve().parent,
        targets=TOOL_MAIN_TARGETS,
        label="validation",
    ).main(argv)
