HERO_DEFORM_STRENGTH_MAX = 0.185 if FINAL_FOR_YOUTUBE else 0.135
HERO_DEFORM_DETAIL_STRENGTH_MAX = 0.072 if FINAL_FOR_YOUTUBE else 0.052
HERO_DEFORM_WAVE_HEIGHT_MAX = 0.115 if FINAL_FOR_YOUTUBE else 0.080
HERO_DEFORM_MAIN_DIM_FACTOR = 0.105 if FINAL_FOR_YOUTUBE else 0.085
HERO_DEFORM_DETAIL_DIM_FACTOR = 0.040 if FINAL_FOR_YOUTUBE else 0.030
HERO_DEFORM_WAVE_DIM_FACTOR = 0.070 if FINAL_FOR_YOUTUBE else 0.052
HERO_DEFORM_TWIST_MAX = math.radians(16.0 if FINAL_FOR_YOUTUBE else 11.0)
HERO_DEFORM_SUBDIV_VIEW = 1
HERO_DEFORM_SUBDIV_RENDER = 2 if FINAL_FOR_YOUTUBE else 1
HERO_DEFORM_NOISE_SIZE = 0.92
HERO_DEFORM_DETAIL_NOISE_SIZE = 0.46
HERO_DEFORM_NOISE_CONTRAST = 3.60
HERO_DEFORM_CONTROLLER_RADIUS = 0.42
HERO_DEFORM_CONTROLLER_Z = PRIMARY_BASE_Z + 1.15
HERO_DEFORM_KEYFRAME_STEP = 2

USE_HERO_MATERIAL_AUDIO_NODES = True
HERO_MATERIAL_EMISSION_MIN = 0.10
HERO_MATERIAL_EMISSION_MAX = 0.68 if FINAL_FOR_YOUTUBE else 0.52
HERO_MATERIAL_SELF_LIGHT_MIN = 0.018
HERO_MATERIAL_SELF_LIGHT_MAX = 0.34 if FINAL_FOR_YOUTUBE else 0.26
HERO_MATERIAL_BUMP_MIN = 0.010
HERO_MATERIAL_BUMP_MAX = 0.088 if FINAL_FOR_YOUTUBE else 0.065
HERO_MATERIAL_ROUGHNESS_MIN = 0.20
HERO_MATERIAL_ROUGHNESS_MAX = 0.58
HERO_MATERIAL_NOISE_SCALE_MIN = 4.0
HERO_MATERIAL_NOISE_SCALE_MAX = 13.5
HERO_MATERIAL_MAPPING_DRIFT = 0.18

# ============================================================
# CAMERA
# ============================================================
CAMERA_BASE_LOCATION = (0.0, -11.5, 5.6)
CAMERA_BASE_LENS = 34
CAMERA_DOF_FSTOP = 3.8 if FINAL_FOR_YOUTUBE else 6.5

CAMERA_BEAT_BUMP_Z = 0.08
CAMERA_BEAT_BUMP_Y = 0.10
CAMERA_ORBIT_AMOUNT = 0.32
CAMERA_PUSH_AMOUNT = 0.45
CAMERA_VERTICAL_SWAY = 0.35

# ============================================================
# LIGHTS
# ============================================================
LIGHT_ENERGY_MIN = 125.0
LIGHT_ENERGY_MAX = 158.0 if FINAL_FOR_YOUTUBE else 142.0
PHYSICS_ACCENT_EMISSION_MIN = 0.14
PHYSICS_ACCENT_EMISSION_MAX = 1.32 if FINAL_FOR_YOUTUBE else 1.05
PHYSICS_ACCENT_MIX_MIN = 0.20
PHYSICS_ACCENT_MIX_MAX = 0.68 if FINAL_FOR_YOUTUBE else 0.55

# ============================================================
# FORCE FIELDS
# ============================================================
FIELD_STRENGTH_MIN = 0.0
FIELD_STRENGTH_MAX = 42.0
HERO_GRAVITY_STRENGTH_MIN = 5.0
HERO_GRAVITY_STRENGTH_MAX = 34.0

TURB_STRENGTH_MIN = 0.25
TURB_STRENGTH_MAX = 4.8

VORTEX_STRENGTH_MIN = 0.15
VORTEX_STRENGTH_MAX = 2.6

# ============================================================
# MIST
# ============================================================
MIST_FLOAT_AMPLITUDE = 0.18
MIST_BEAT_BOOST = 0.06

# ============================================================
# PALETTE
# ============================================================
PEACE_PALETTE = {
    "twilight_blue": (0.020, 0.032, 0.060, 1.0),
    "soft_teal": (0.170, 0.460, 0.480, 1.0),
    "muted_gold": (0.720, 0.620, 0.340, 1.0),
    "dust_rose": (0.500, 0.300, 0.340, 1.0),
    "warm_white": (0.940, 0.930, 0.900, 1.0),
}

PALETTE_LIST = [
    PEACE_PALETTE["soft_teal"],
    PEACE_PALETTE["muted_gold"],
    PEACE_PALETTE["dust_rose"],
    PEACE_PALETTE["warm_white"],
]
