"""Template generation for track input contract."""
from __future__ import annotations

from typing import Any

from .constants import INPUT_ROLES


def build_template(track_name: str) -> dict[str, Any]:
    return {
        "kind": "full0to10_track_input_template",
        "track_name": track_name,
        "description": "Fill these paths to remove startup track input warnings.",
        "inputs": {
            role: {
                "path": "",
                "required": True,
                "description": description,
            }
            for role, description in {
                "analysis_json": "Audio/WAV analysis JSON generated by the analysis pipeline.",
                "music_context_json": "Music/context JSON describing mood, sections, BPM, structure or semantic context.",
                "blender_keyframes_json": "Blender-ready keyframes JSON for animation timing.",
            }.items()
        },
        "required_roles": list(INPUT_ROLES),
        "notes": [
            "This template is generated evidence, not source input.",
            "Do not commit private/audio-specific generated JSON unless intentionally versioned.",
            "Prefer storing track-specific inputs under output or a local ignored input folder.",
        ],
    }
